#ifdef XVT_OPT

#define xvt_app_allow_quit              xvtk_app_allow_quit
#define xvt_app_destroy                 xvtv_app_destroy
#define xvt_app_get_files_count         xvtk_app_get_files_count
#define xvt_app_set_file_processed      xvtk_app_set_file_processed
#define xvt_app_get_file                xvtk_app_get_file
#define xvt_app_get_default_ctools      xvtv_app_get_default_ctools
#define xvt_app_process_pending_events  xvtk_app_process_pending_events

#define xvt_cb_alloc_data               xvtk_cb_alloc_data
#define xvt_cb_close                    xvtk_cb_close
#define xvt_cb_free_data                xvtk_cb_free_data
#define xvt_cb_open                     xvtk_cb_open
#define xvt_cb_get_data                 xvtk_cb_get_data
#define xvt_cb_has_format               xvtk_cb_has_format
#define xvt_cb_put_data                 xvtk_cb_put_data

#define xvt_ctl_create                  xvtk_ctl_create
#define xvt_ctl_create_def              xvtk_ctl_create_def
#define xvt_ctl_is_checked              xvtk_ctl_is_checked
#define xvt_ctl_set_text_sel            xvtk_ctl_set_text_sel
#define xvt_ctl_get_text_sel            xvtk_ctl_get_text_sel
#define xvt_ctl_set_checked             xvtk_ctl_set_checked
#define xvt_ctl_check_radio_button      xvtk_ctl_check_radio_button

#define xvt_cxo_call_next               xvtv_cxo_call_next
#define xvt_cxo_create                  xvtv_cxo_create
#define xvt_cxo_destroy                 xvtv_cxo_destroy
#define xvt_cxo_dispatch_msg            xvtv_cxo_dispatch_msg
#define xvt_cxo_get_class_name          xvtv_cxo_get_class_name
#define xvt_cxo_is_valid                xvtv_cxo_is_valid

#define xvt_dlg_create_def              xvtk_dlg_create_def
#define xvt_dlg_create_res              xvtk_dlg_create_res

#define xvt_dm_post_about_box           xvtv_dm_post_about_box
#define xvt_dm_post_file_open           xvtv_dm_post_file_open
#define xvt_dm_post_file_save           xvtv_dm_post_file_save
#define xvt_dm_post_font_sel            xvtv_dm_post_font_sel
#define xvt_dm_post_page_setup          xvtv_dm_post_page_setup
#define xvt_dm_post_string_prompt       xvtv_dm_post_string_prompt

#define xvt_dwin_clear                  xvtv_dwin_clear
#define xvt_dwin_close_pict             xvtk_dwin_close_pict
#define xvt_dwin_draw_aline             xvtk_dwin_draw_aline
#define xvt_dwin_draw_arc               xvtk_dwin_draw_arc
#define xvt_dwin_draw_icon              xvtk_dwin_draw_icon
#define xvt_dwin_draw_image             xvtk_dwin_draw_image
#define xvt_dwin_draw_line              xvtk_dwin_draw_line
#define xvt_dwin_draw_oval              xvtk_dwin_draw_oval
#define xvt_dwin_draw_pict              xvtk_dwin_draw_pict
#define xvt_dwin_draw_pie               xvtk_dwin_draw_pie
#define xvt_dwin_draw_pmap              xvtk_dwin_draw_pmap
#define xvt_dwin_draw_polygon           xvtk_dwin_draw_polygon
#define xvt_dwin_draw_polyline          xvtk_dwin_draw_polyline
#define xvt_dwin_draw_rect              xvtk_dwin_draw_rect
#define xvt_dwin_draw_roundrect         xvtk_dwin_draw_roundrect
#define xvt_dwin_draw_set_pos           xvtk_dwin_draw_set_pos
#define xvt_dwin_draw_text              xvtk_dwin_draw_text
#define xvt_dwin_get_clip               xvtk_dwin_get_clip
#define xvt_dwin_get_font               xvtk_dwin_get_font
#define xvt_dwin_get_text_width         xvtk_dwin_get_text_width
#define xvt_dwin_invalidate_rect        xvtk_dwin_invalidate_rect
#define xvt_dwin_is_update_needed       xvtk_dwin_is_update_needed
#define xvt_dwin_open_pict              xvtk_dwin_open_pict
#define xvt_dwin_scroll_rect            xvtk_dwin_scroll_rect
#define xvt_dwin_set_back_color         xvtk_dwin_set_back_color
#define xvt_dwin_set_cbrush             xvtk_dwin_set_cbrush
#define xvt_dwin_set_clip               xvtk_dwin_set_clip
#define xvt_dwin_set_cpen               xvtk_dwin_set_cpen
#define xvt_dwin_set_draw_ctools        xvtk_dwin_set_draw_ctools
#define xvt_dwin_set_draw_mode          xvtk_dwin_set_draw_mode
#define xvt_dwin_set_font               xvtv_dwin_set_font
#define xvt_dwin_get_font_app_data      xvtv_dwin_get_font_app_data
#define xvt_dwin_get_font_size          xvtv_dwin_get_font_size
#define xvt_dwin_get_font_size_mapped   xvtv_dwin_get_font_size_mapped
#define xvt_dwin_get_font_style         xvtv_dwin_get_font_style
#define xvt_dwin_get_font_style_mapped  xvtv_dwin_get_font_style_mapped
#define xvt_dwin_set_font_app_data      xvtv_dwin_set_font_app_data
#define xvt_dwin_set_font_family        xvtv_dwin_set_font_family
#define xvt_dwin_set_font_native_desc   xvtv_dwin_set_font_native_desc
#define xvt_dwin_set_font_size          xvtv_dwin_set_font_size
#define xvt_dwin_set_font_style         xvtv_dwin_set_font_style
#define xvt_dwin_set_fore_color         xvtk_dwin_set_fore_color
#define xvt_dwin_set_std_cbrush         xvtv_dwin_set_std_cbrush
#define xvt_dwin_set_std_cpen           xvtv_dwin_set_std_cpen
#define xvt_dwin_update                 xvtk_dwin_update

#define xvt_errmsg_dispatch             xvtv_errmsg_dispatch
#define xvt_errmsg_dispatch_s           xvtv_errmsg_dispatch_s
#define xvt_errmsg_push_handler         xvtv_errmsg_push_handler
#define xvt_errmsg_pop_handler          xvtv_errmsg_pop_handler
#define xvt_errmsg_get_sev_id           xvtv_errmsg_get_sev_id
#define xvt_errmsg_get_sev_text         xvtv_errmsg_get_sev_text
#define xvt_errmsg_get_msg_id           xvtv_errmsg_get_msg_id
#define xvt_errmsg_get_msg_text         xvtv_errmsg_get_msg_text
#define xvt_errmsg_get_cat_text         xvtv_errmsg_get_cat_text
#define xvt_errmsg_get_code_line        xvtv_errmsg_get_code_line
#define xvt_errmsg_get_code_file        xvtv_errmsg_get_code_file
#define xvt_errmsg_get_api_name         xvtv_errmsg_get_api_name
#define xvt_errmsg_get_tgt_object       xvtv_errmsg_get_tgt_object
#define xvt_errmsg_get_text             xvtv_errmsg_get_text

#define xvt_event_get_font              xvtv_event_get_font
#define xvt_event_is_virtual_key        xvtv_event_is_virtual_key
#define xvt_event_set_font              xvtv_event_set_font

#define xvt_fmap_get_families           xvtv_fmap_get_families
#define xvt_fmap_get_family_styles      xvtv_fmap_get_family_styles
#define xvt_fmap_get_familysize_styles  xvtv_fmap_get_familysize_styles
#define xvt_fmap_get_family_sizes       xvtv_fmap_get_family_sizes
#define xvt_fmap_get_familystyle_sizes  xvtv_fmap_get_familystyle_sizes

#define xvt_font_copy                   xvtv_font_copy
#define xvt_font_create                 xvtv_font_create
#define xvt_font_map_using_default      xvtv_font_map_using_default
#define xvt_font_deserialize            xvtv_font_deserialize
#define xvt_font_get_app_data           xvtv_font_get_app_data
#define xvt_font_get_metrics            xvtk_font_get_metrics
#define xvt_font_get_size               xvtv_font_get_size
#define xvt_font_get_size_mapped        xvtk_font_get_size_mapped
#define xvt_font_get_style              xvtv_font_get_style
#define xvt_font_get_style_mapped       xvtk_font_get_style_mapped
#define xvt_font_get_win                xvtv_font_get_win
#define xvt_font_is_mapped              xvtv_font_is_mapped
#define xvt_font_is_print               xvtk_font_is_print
#define xvt_font_is_scalable            xvtk_font_is_scalable
#define xvt_font_is_valid               xvtv_font_is_valid
#define xvt_font_map                    xvtv_font_map
#define xvt_font_serialize              xvtv_font_serialize
#define xvt_font_set_app_data           xvtv_font_set_app_data
#define xvt_font_set_family             xvtv_font_set_family
#define xvt_font_set_native_desc        xvtv_font_set_native_desc
#define xvt_font_set_size               xvtv_font_set_size
#define xvt_font_set_style              xvtv_font_set_style

#define xvt_fsys_set_file_attr          xvtv_fsys_set_file_attr
#define xvt_fsys_get_file_attr          xvtv_fsys_get_file_attr
#define xvt_fsys_convert_dir_to_str     xvtk_fsys_convert_dir_to_str
#define xvt_fsys_convert_str_to_dir     xvtk_fsys_convert_str_to_dir
#define xvt_fsys_get_default_dir        xvtk_fsys_get_default_dir
#define xvt_fsys_get_dir                xvtk_fsys_get_dir
#define xvt_fsys_set_dir_startup        xvtk_fsys_set_dir_startup
#define xvt_fsys_list_files             xvtk_fsys_list_files
#define xvt_fsys_rem_file               xvtv_fsys_rem_file
#define xvt_fsys_restore_dir            xvtk_fsys_restore_dir
#define xvt_fsys_save_dir               xvtk_fsys_save_dir
#define xvt_fsys_set_dir                xvtk_fsys_set_dir
#define xvt_fsys_parse_pathname         xvtk_fsys_parse_pathname
#define xvt_fsys_build_pathname         xvtk_fsys_build_pathname

#define xvt_gmem_alloc                  xvtv_gmem_alloc
#define xvt_gmem_free                   xvtv_gmem_free
#define xvt_gmem_lock                   xvtv_gmem_lock
#define xvt_gmem_realloc                xvtv_gmem_realloc
#define xvt_gmem_get_size               xvtv_gmem_get_size
#define xvt_gmem_unlock                 xvtv_gmem_unlock

#define xvt_image_create                xvtv_image_create
#define xvt_image_destroy               xvtv_image_destroy
#define xvt_image_duplicate             xvtv_image_duplicate
#define xvt_image_fill_rect             xvtv_image_fill_rect
#define xvt_image_get_clut              xvtv_image_get_clut
#define xvt_image_get_dimensions        xvtv_image_get_dimensions
#define xvt_image_get_format            xvtv_image_get_format
#define xvt_image_get_from_pmap         xvtk_image_get_from_pmap
#define xvt_image_get_ncolors           xvtv_image_get_ncolors
#define xvt_image_get_pixel             xvtv_image_get_pixel
#define xvt_image_get_resolution        xvtv_image_get_resolution
#define xvt_image_get_scanline          xvtv_image_get_scanline
#define xvt_image_read                  xvtv_image_read
#define xvt_image_read_bmp              xvtv_image_read_bmp_from_fn
#define xvt_image_read_xbm              xvtv_image_read_xbm_from_fn
#define xvt_image_read_xpm              xvtv_image_read_xpm_from_fn
#define xvt_image_set_clut              xvtv_image_set_clut
#define xvt_image_set_pixel             xvtv_image_set_pixel
#define xvt_image_set_resolution        xvtv_image_set_resolution
#define xvt_image_transfer              xvtv_image_transfer

#define xvt_list_add                    xvtv_list_add
#define xvt_list_clear                  xvtk_list_clear
#define xvt_list_count_all              xvtk_list_count_all
#define xvt_list_count_sel              xvtk_list_count_sel
#define xvt_list_get_all                xvtk_list_get_all
#define xvt_list_get_elt                xvtk_list_get_elt
#define xvt_list_get_first_sel          xvtk_list_get_first_sel
#define xvt_list_get_sel                xvtk_list_get_sel
#define xvt_list_get_sel_index          xvtk_list_get_sel_index
#define xvt_list_is_sel                 xvtk_list_is_sel
#define xvt_list_rem                    xvtk_list_rem
#define xvt_list_resume                 xvtk_list_resume
#define xvt_list_set_sel                xvtk_list_set_sel
#define xvt_list_suspend                xvtk_list_suspend

#define xvt_mem_alloc                   xvtv_mem_alloc
#define xvt_mem_free                    xvtv_mem_free
#define xvt_mem_realloc                 xvtv_mem_realloc
#define xvt_mem_rep                     xvtv_mem_rep
#define xvt_mem_zalloc                  xvtv_mem_zalloc

#define xvt_menu_get_font_sel           xvtk_menu_get_font_sel
#define xvt_menu_get_tree               xvtk_menu_get_tree
#define xvt_menu_set_font_sel           xvtk_menu_set_font_sel
#define xvt_menu_set_item_checked       xvtk_menu_set_item_checked
#define xvt_menu_set_item_enabled       xvtk_menu_set_item_enabled
#define xvt_menu_set_item_title         xvtk_menu_set_item_title
#define xvt_menu_set_tree               xvtk_menu_set_tree
#define xvt_menu_update                 xvtk_menu_update
#define xvt_menu_popup                  xvtk_menu_popup

#define xvt_nav_destroy                 xvtv_nav_destroy
#define xvt_nav_rem_win                 xvtv_nav_rem_win
#define xvt_nav_list_wins               xvtv_nav_list_wins

#define xvt_palet_create                xvtv_palet_create
#define xvt_palet_destroy               xvtv_palet_destroy
#define xvt_palet_default               xvtv_palet_default
#define xvt_palet_get_type              xvtv_palet_get_type
#define xvt_palet_get_size              xvtv_palet_get_size
#define xvt_palet_get_ncolors           xvtv_palet_get_ncolors
#define xvt_palet_set_tolerance         xvtv_palet_set_tolerance
#define xvt_palet_get_tolerance         xvtv_palet_get_tolerance
#define xvt_palet_add_colors            xvtv_palet_add_colors
#define xvt_palet_add_colors_from_image xvtv_palet_add_colors_from_image
#define xvt_palet_get_colors            xvtv_palet_get_colors

#define xvt_pict_create                 xvtk_pict_create
#define xvt_pict_destroy                xvtk_pict_destroy
#define xvt_pict_lock                   xvtk_pict_lock
#define xvt_pict_unlock                 xvtk_pict_unlock

#define xvt_pmap_create                 xvtk_pmap_create
#define xvt_pmap_destroy                xvtk_vobj_destroy

#define xvt_print_close                 xvtk_print_close
#define xvt_print_close_page            xvtk_print_close_page
#define xvt_print_create                xvtk_print_create
#define xvt_print_create_win            xvtk_print_create_win
#define xvt_print_destroy               xvtk_print_destroy
#define xvt_print_get_next_band         xvtk_print_get_next_band
#define xvt_print_is_valid              xvtk_print_is_valid
#define xvt_print_open                  xvtk_print_open
#define xvt_print_open_page             xvtk_print_open_page
#define xvt_print_start_thread          xvtk_print_start_thread

#define xvt_rect_get_height             xvtv_rect_get_height
#define xvt_rect_get_width              xvtv_rect_get_width
#define xvt_rect_has_point              xvtv_rect_has_point
#define xvt_rect_intersect              xvtv_rect_intersect
#define xvt_rect_is_empty               xvtv_rect_is_empty
#define xvt_rect_offset                 xvtv_rect_offset
#define xvt_rect_set                    xvtv_rect_set
#define xvt_rect_set_empty              xvtv_rect_set_empty
#define xvt_rect_set_height             xvtv_rect_set_height
#define xvt_rect_set_pos                xvtv_rect_set_pos
#define xvt_rect_set_width              xvtv_rect_set_width

#define xvt_res_free_menu_tree          xvtv_res_free_menu_tree
#define xvt_res_free_win_def            xvtv_res_free_win_def
#define xvt_res_get_dlg_def             xvtv_res_get_dlg_def
#define xvt_res_get_dlg_data            xvtv_res_get_dlg_data
#define xvt_res_get_font                xvtv_res_get_font
#define xvt_res_get_image               xvtv_res_get_image
#define xvt_res_get_image_data          xvtv_res_get_image_data
#define xvt_res_get_menu                xvtv_res_get_menu
#define xvt_res_get_menu_data           xvtv_res_get_menu_data
#define xvt_res_get_str                 xvtv_res_get_str
#define xvt_res_get_str_list            xvtv_res_get_str_list
#define xvt_res_get_win_data            xvtv_res_get_win_data
#define xvt_res_get_win_def             xvtv_res_get_win_def

#define xvt_sbar_get_pos                xvtk_sbar_get_pos
#define xvt_sbar_get_proportion         xvtk_sbar_get_proportion
#define xvt_sbar_get_range              xvtk_sbar_get_range
#define xvt_sbar_set_pos                xvtk_sbar_set_pos
#define xvt_sbar_set_proportion         xvtk_sbar_set_proportion
#define xvt_sbar_set_range              xvtk_sbar_set_range

#define xvt_scr_beep                    xvtk_scr_beep
#define xvt_scr_get_focus_topwin        xvtv_scr_get_focus_topwin
#define xvt_scr_get_focus_vobj          xvtk_scr_get_focus_vobj
#define xvt_scr_hide_cursor             xvtk_scr_hide_cursor
#define xvt_scr_list_wins               xvtv_scr_list_wins
#define xvt_scr_set_busy_cursor         xvtk_scr_set_busy_cursor

#define xvt_slist_add_at_elt            xvtv_slist_add_at_elt
#define xvt_slist_add_at_pos            xvtv_slist_add_at_pos
#define xvt_slist_add_sorted            xvtv_slist_add_sorted
#define xvt_slist_count                 xvtv_slist_count
#define xvt_slist_create                xvtv_slist_create
#define xvt_slist_debug                 xvtv_slist_debug
#define xvt_slist_destroy               xvtv_slist_destroy
#define xvt_slist_get                   xvtv_slist_get
#define xvt_slist_get_data              xvtv_slist_get_data
#define xvt_slist_get_elt               xvtv_slist_get_elt
#define xvt_slist_get_first             xvtv_slist_get_first
#define xvt_slist_get_next              xvtv_slist_get_next
#define xvt_slist_is_valid              xvtv_slist_is_valid
#define xvt_slist_rem                   xvtv_slist_rem

#define xvt_str_collate                xvtv_str_collate
#define xvt_str_collate_ignoring_case  xvtv_str_collate_ignoring_case
#define xvt_str_compare                xvtv_str_compare
#define xvt_str_compare_ignoring_case  xvtv_str_compare_ignoring_case
#define xvt_str_compare_n_char         xvtv_str_compare_n_char
#define xvt_str_compare_wchar          xvtv_str_compare_wchar
#define xvt_str_concat                 xvtv_str_concat
#define xvt_str_concat_n_char          xvtv_str_concat_n_char
#define xvt_str_convert_mb_to_wc       xvtk_str_convert_mb_to_wc
#define xvt_str_convert_mbs_to_wcs     xvtv_str_convert_mbs_to_wcs
#define xvt_str_convert_to_lower       xvtk_str_convert_to_lower
#define xvt_str_convert_to_upper       xvtk_str_convert_to_upper
#define xvt_str_convert_wc_to_mb       xvtk_str_convert_wc_to_mb
#define xvt_str_convert_wchar_to_lower xvtv_str_convert_wchar_to_lower
#define xvt_str_convert_wchar_to_upper xvtv_str_convert_wchar_to_upper
#define xvt_str_convert_wcs_to_mbs     xvtv_str_convert_wcs_to_mbs
#define xvt_str_copy                   xvtv_str_copy
#define xvt_str_copy_n_char            xvtv_str_copy_n_char
#define xvt_str_copy_n_size            xvtv_str_copy_n_size
#define xvt_str_duplicate              xvtv_str_duplicate
#define xvt_str_find_char_set          xvtv_str_find_char_set
#define xvt_str_find_first_char        xvtv_str_find_first_char
#define xvt_str_find_first_wchar       xvtv_str_find_first_wchar
#define xvt_str_find_last_char         xvtv_str_find_last_char
#define xvt_str_find_last_wchar        xvtv_str_find_last_wchar
#define xvt_str_find_not_char_set      xvtv_str_find_not_char_set
#define xvt_str_find_substring         xvtv_str_find_substring
#define xvt_str_find_token             xvtv_str_find_token
#define xvt_str_get_byte_count         xvtv_str_get_byte_count
#define xvt_str_get_char_count         xvtv_str_get_char_count
#define xvt_str_get_char_size          xvtk_str_get_char_size
#define xvt_str_get_mnemonic           xvtv_str_get_mnemonic
#define xvt_str_get_next_char          xvtk_str_get_next_char
#define xvt_str_get_n_char_count       xvtv_str_get_n_char_count
#define xvt_str_get_n_char_size        xvtv_str_get_n_char_size
#define xvt_str_is_alnum               xvtv_str_is_alnum
#define xvt_str_is_alpha               xvtv_str_is_alpha
#define xvt_str_is_cntrl               xvtv_str_is_cntrl
#define xvt_str_is_digit               xvtv_str_is_digit
#define xvt_str_is_equal               xvtv_str_is_equal
#define xvt_str_is_graph               xvtv_str_is_graph
#define xvt_str_is_invariant           xvtv_str_is_invariant
#define xvt_str_is_lower               xvtv_str_is_lower
#define xvt_str_is_print               xvtv_str_is_print
#define xvt_str_is_punct               xvtv_str_is_punct
#define xvt_str_is_space               xvtv_str_is_space
#define xvt_str_is_upper               xvtv_str_is_upper
#define xvt_str_is_xdigit              xvtv_str_is_xdigit
#define xvt_str_match                  xvtv_str_match
#define xvt_str_parse_double           xvtv_str_parse_double
#define xvt_str_parse_long             xvtv_str_parse_long
#define xvt_str_parse_ulong            xvtv_str_parse_ulong
#define xvt_str_mnemonic               xvtv_str_set_mnemonic
#define xvt_str_vsprintf               xvtv_str_vsprintf

#define xvt_timer_create               xvtk_timer_create
#define xvt_timer_destroy              xvtk_timer_destroy

#define xvt_tx_add_par                 xvtv_tx_add_par
#define xvt_tx_append                  xvtv_tx_append
#define xvt_tx_clear                   xvtv_tx_clear
#define xvt_tx_create                  xvtv_tx_create
#define xvt_tx_create_def              xvtv_tx_create_def
#define xvt_tx_destroy                 xvtv_tx_destroy
#define xvt_tx_get_active              xvtv_tx_get_active
#define xvt_tx_get_attr                xvtv_tx_get_attr
#define xvt_tx_get_cid                 xvtv_tx_get_cid
#define xvt_tx_get_data                xvtv_tx_get_data
#define xvt_tx_get_font                xvtv_tx_get_font
#define xvt_tx_get_limit               xvtv_tx_get_limit
#define xvt_tx_get_line                xvtv_tx_get_line
#define xvt_tx_get_margin              xvtv_tx_get_margin
#define xvt_tx_get_next_tx             xvtv_tx_get_next_tx
#define xvt_tx_get_num_chars           xvtv_tx_get_num_chars
#define xvt_tx_get_num_lines           xvtv_tx_get_num_lines
#define xvt_tx_get_num_par_lines       xvtv_tx_get_num_par_lines
#define xvt_tx_get_num_pars            xvtv_tx_get_num_pars
#define xvt_tx_get_origin              xvtv_tx_get_origin
#define xvt_tx_get_rect                xvtv_tx_get_rect
#define xvt_tx_get_sel                 xvtv_tx_get_sel
#define xvt_tx_get_tabstop             xvtv_tx_get_tabstop
#define xvt_tx_get_view                xvtv_tx_get_view
#define xvt_tx_get_win                 xvtv_tx_get_win
#define xvt_tx_is_scroll_update        xvtv_tx_is_scroll_update
#define xvt_tx_move                    xvtv_tx_move
#define xvt_tx_process_event           xvtv_tx_process_event
#define xvt_tx_rem_par                 xvtv_tx_rem_par
#define xvt_tx_reset                   xvtv_tx_reset
#define xvt_tx_resume                  xvtv_tx_resume
#define xvt_tx_scroll_hor              xvtv_tx_scroll_hor
#define xvt_tx_scroll_vert             xvtv_tx_scroll_vert
#define xvt_tx_set_active              xvtv_tx_set_active
#define xvt_tx_set_attr                xvtv_tx_set_attr
#define xvt_tx_set_colors              xvtv_tx_set_colors
#define xvt_tx_set_data                xvtv_tx_set_data
#define xvt_tx_set_font                xvtv_tx_set_font
#define xvt_tx_set_limit               xvtv_tx_set_limit
#define xvt_tx_set_margin              xvtv_tx_set_margin
#define xvt_tx_set_par                 xvtv_tx_set_par
#define xvt_tx_set_scroll_callback     xvtv_tx_set_scroll_callback
#define xvt_tx_set_sel                 xvtv_tx_set_sel
#define xvt_tx_set_tabstop             xvtv_tx_set_tabstop
#define xvt_tx_suspend                 xvtv_tx_suspend

#define xvt_vobj_destroy               xvtk_vobj_destroy
#define xvt_vobj_get_client_rect       xvtk_vobj_get_client_rect
#define xvt_vobj_get_flags             xvtk_vobj_get_flags
#define xvt_vobj_get_outer_rect        xvtk_vobj_get_outer_rect
#define xvt_vobj_get_palet             xvtv_vobj_get_palet
#define xvt_vobj_is_focusable          xvtk_vobj_is_focusable
#define xvt_vobj_is_valid              xvtv_vobj_is_valid
#define xvt_vobj_set_enabled           xvtk_vobj_set_enabled
#define xvt_vobj_set_title             xvtv_vobj_set_title
#define xvt_vobj_set_visible           xvtk_vobj_set_visible
#define xvt_vobj_translate_points      xvtk_vobj_translate_points

#define xvt_win_create                 xvtk_win_create
#define xvt_win_create_def             xvtk_win_create_def
#define xvt_win_create_res             xvtv_win_create_res
#define xvt_win_dispatch_event         xvtk_win_dispatch_event
#define xvt_win_enum_wins              xvtv_win_enum_wins
#define xvt_win_get_ctl                xvtk_win_get_ctl
#define xvt_win_get_ctl_colors         xvtk_win_get_ctl_colors
#define xvt_win_get_ctl_font           xvtk_win_get_ctl_font
#define xvt_win_get_cxo                xvtv_win_get_cxo
#define xvt_win_get_nav                xvtv_win_get_nav
#define xvt_win_get_tx                 xvtv_win_get_tx
#define xvt_win_list_cxos              xvtv_win_list_cxos
#define xvt_win_list_wins              xvtv_win_list_wins
#define xvt_win_release_pointer        xvtk_win_release_pointer
#define xvt_win_set_caret_pos          xvtk_win_set_caret_pos
#define xvt_win_set_caret_size         xvtk_win_set_caret_size
#define xvt_win_set_caret_visible      xvtk_win_set_caret_visible
#define xvt_win_set_ctl_font           xvtv_win_set_ctl_font
#define xvt_win_set_cursor             xvtk_win_set_cursor
#define xvt_win_set_doc_title          xvtk_win_set_doc_title
#define xvt_win_trap_pointer           xvtk_win_trap_pointer

#endif

