-- V0.0.1

-- 03_create_tables

-- Generated by Oracle SQL Developer Data Modeler 3.0.0.665
--   at:        2011-06-07 13:15:59 MESZ
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g



CREATE TABLE Cross_Section
    (
     ID NUMBER (20)  NOT NULL ,
     Name VARCHAR2 (50)  NOT NULL ,
     Line MDSYS.SDO_GEOMETRY ,
     Station NUMBER (8,1)  NOT NULL ,
     Creation_Date TIMESTAMP (0)  NOT NULL ,
     Editing_Date TIMESTAMP (0)  NOT NULL ,
     Editing_User VARCHAR2 (50)  NOT NULL ,
     Measurement_Date TIMESTAMP (0) , 
     Description VARCHAR2 (255) ,
     Water_Body NUMBER (20)  NOT NULL ,
     State NUMBER (20)  NOT NULL
    )
;


CREATE UNIQUE INDEX "Cross_Section PKX" ON Cross_Section
    (
     ID ASC
    )
;
CREATE UNIQUE INDEX "Cross_Section Name UKX" ON Cross_Section
    (
     Name ASC ,
     State ASC
    )
;
CREATE INDEX State__CSX ON Cross_Section
    (
     State ASC
    )
;
CREATE INDEX Water_Body__CSX ON Cross_Section
    (
     Water_Body ASC
    )
;

ALTER TABLE Cross_Section
    ADD CONSTRAINT "Cross_Section PK" PRIMARY KEY ( ID ) ;

ALTER TABLE Cross_Section
    ADD CONSTRAINT "Cross_Section Name UK" UNIQUE ( Name , State ) ;


CREATE TABLE Cross_Section_Part
    (
     ID NUMBER (20)  NOT NULL ,
     Name VARCHAR2 (50)  NOT NULL ,
     Line MDSYS.SDO_GEOMETRY ,
     Category VARCHAR2 (50)  NOT NULL ,
     Description VARCHAR2 (255) ,
     Cross_Section NUMBER (20)  NOT NULL
    )
;

CREATE UNIQUE INDEX "Cross_Section_Part PKX" ON Cross_Section_Part
    (
     ID ASC
    )
;
CREATE UNIQUE INDEX "Cross_Section_Part Name UKX" ON Cross_Section_Part
    (
     Name ASC ,
     Cross_Section ASC
    )
;
CREATE INDEX CS__CS_PartX ON Cross_Section_Part
    (
     Cross_Section ASC
    )
;

ALTER TABLE Cross_Section_Part
    ADD CONSTRAINT "Cross_Section_Part PK" PRIMARY KEY ( ID ) ;

ALTER TABLE Cross_Section_Part
    ADD CONSTRAINT "Cross_Section_Part Name UK" UNIQUE ( Name , Cross_Section ) ;


CREATE TABLE Event
    (
     ID NUMBER (20)  NOT NULL ,
     Name VARCHAR2 (100)  NOT NULL ,
     Creation_Date TIMESTAMP (0)  NOT NULL ,
     Editing_Date TIMESTAMP (0)  NOT NULL ,
     Editing_User VARCHAR2 (50)  NOT NULL ,
     Measurement_Date TIMESTAMP (0) ,
     Source VARCHAR2 (255) ,
     Type VARCHAR2 (50) DEFAULT 'Measurement' CHECK ( Type IN ('Measurement', 'Other', 'Simulation')) ,
     Description VARCHAR2 (255) ,
     Water_Body NUMBER (20)  NOT NULL
    )
;


CREATE UNIQUE INDEX "Event PKX" ON Event
    (
     ID ASC
    )
;
CREATE UNIQUE INDEX "Event Name UKX" ON Event
    (
     Name ASC
    )
;
CREATE INDEX Water_Body__EventX ON Event
    (
     Water_Body ASC
    )
;

ALTER TABLE Event
    ADD CONSTRAINT "Event PK" PRIMARY KEY ( ID ) ;

ALTER TABLE Event
    ADD CONSTRAINT "Event Name UK" UNIQUE ( Name ) ;


CREATE TABLE Info
    (
     Key VARCHAR2 (50)  NOT NULL ,
     Value VARCHAR2 (255)
    )
;


CREATE UNIQUE INDEX "Info PKX" ON Info
    (
     Key ASC
    )
;

ALTER TABLE Info
    ADD CONSTRAINT "Info PK" PRIMARY KEY ( Key ) ;

    -- Version setzen auf "creating" oder "updateing"
INSERT INTO INFO("KEY", "VALUE") VALUES ('Version', 'creating 0.0.1');

CREATE TABLE Point
    (
     ID NUMBER (20)  NOT NULL ,
     Name VARCHAR2 (50)  NOT NULL ,
     Location MDSYS.SDO_GEOMETRY ,
     Consecutive_Num NUMBER (11)  NOT NULL ,
     Code VARCHAR2 (50) ,
     HyK VARCHAR2 (50) ,
     Width NUMBER (8,4) ,
     Height NUMBER (8,4) ,
     Roughness_Point_Kind VARCHAR2 (50) ,
     Roughness_K_Value NUMBER (10,3) ,
     Roughness_Kst_Value NUMBER (8,1) ,
     Vegetation_Dp NUMBER (8,3) ,
     Vegetation_Ax NUMBER (8,3) ,
     Vegetation_Ay NUMBER (8,3) ,
     Description VARCHAR2 (255) ,
     Vegetation_Point_Kind VARCHAR2 (50) ,
     Vegetation VARCHAR2 (50) ,
     Roughness VARCHAR2 (50) ,
     Cross_Section_Part NUMBER (20)  NOT NULL
    )
;


CREATE UNIQUE INDEX "Point PKX" ON Point
    (
     ID ASC
    )
;
CREATE INDEX CS_Part__PointX ON Point
    (
     Cross_Section_Part ASC
    )
;
CREATE INDEX Roughness__PointX ON Point
    (
     Roughness_Point_Kind ASC ,
     Roughness ASC
    )
;
CREATE INDEX Vegetation__PointX ON Point
    (
     Vegetation_Point_Kind ASC ,
     Vegetation ASC
    )
;

ALTER TABLE Point
    ADD CONSTRAINT "Point PK" PRIMARY KEY ( ID ) ;


CREATE TABLE Point_Kind
    (
     Name VARCHAR2 (50)  NOT NULL ,
     Label VARCHAR2 (100)  NOT NULL ,
     Description VARCHAR2 (255)
    )
;


CREATE UNIQUE INDEX "Point_Kind PKX" ON Point_Kind
    (
     Name ASC
    )
;

ALTER TABLE Point_Kind
    ADD CONSTRAINT "Point_Kind PK" PRIMARY KEY ( Name ) ;


CREATE TABLE Roughness
    (
     Name VARCHAR2 (50)  NOT NULL ,
     K_Value NUMBER (10,3) ,
     Kst_Value NUMBER (8,1) ,
     Label VARCHAR2 (100) ,
     Source VARCHAR2 (255) ,
     Validity VARCHAR2 (255) ,
     Description VARCHAR2 (255) ,
     Point_Kind VARCHAR2 (50)  NOT NULL
    )
;


CREATE UNIQUE INDEX "Roughness PKX" ON Roughness
    (
     Point_Kind ASC ,
     Name ASC
    )
;
CREATE INDEX Point_Kind__RoughnessX ON Roughness
    (
     Point_Kind ASC
    )
;

ALTER TABLE Roughness
    ADD CONSTRAINT "Roughness PK" PRIMARY KEY ( Point_Kind, Name ) ;


CREATE TABLE State
    (
     ID NUMBER (20)  NOT NULL ,
     Name VARCHAR2 (100)  NOT NULL ,
     IsStateZero CHAR (1) DEFAULT 'F'  NOT NULL ,
     Creation_Date TIMESTAMP (0)  NOT NULL ,
     Editing_Date TIMESTAMP (0)  NOT NULL ,
     Editing_User VARCHAR2 (50)  NOT NULL ,
     Measurement_Date TIMESTAMP (0) ,
     Source VARCHAR2 (255) ,
     Description VARCHAR2 (255)
    )
;


CREATE UNIQUE INDEX "State PKX" ON State
    (
     ID ASC
    )
;
CREATE UNIQUE INDEX "State Name UKX" ON State
    (
     Name ASC
    )
;

ALTER TABLE State
    ADD CONSTRAINT "State PK" PRIMARY KEY ( ID ) ;

ALTER TABLE State
    ADD CONSTRAINT "State Name UK" UNIQUE ( Name ) ;


CREATE TABLE Vegetation
    (
     Name VARCHAR2 (50)  NOT NULL ,
     Dp NUMBER (8,3)  NOT NULL ,
     Ax NUMBER (8,3)  NOT NULL ,
     Ay NUMBER (8,3)  NOT NULL ,
     Label VARCHAR2 (100) ,
     Source VARCHAR2 (255) ,
     Description VARCHAR2 (255) ,
     Point_Kind VARCHAR2 (50)  NOT NULL
    )
;


CREATE UNIQUE INDEX "Vegetation PKX" ON Vegetation
    (
     Point_Kind ASC ,
     Name ASC
    )
;
CREATE INDEX Point_Kind__VegetationX ON Vegetation
    (
     Point_Kind ASC
    )
;

ALTER TABLE Vegetation
    ADD CONSTRAINT "Vegetation PK" PRIMARY KEY ( Point_Kind, Name ) ;


CREATE TABLE Water_Body
    (
     ID NUMBER (20)  NOT NULL ,
     Name VARCHAR2 (100)  NOT NULL ,
     Riverline MDSYS.SDO_GEOMETRY ,
     Label VARCHAR2 (100)  NOT NULL ,
     Direction_of_Stationing VARCHAR2 (20) DEFAULT 'upstream'  NOT NULL CHECK ( Direction_of_Stationing IN ('downstream', 'upstream')) ,
     Rank INTEGER DEFAULT -1 ,
     Description VARCHAR2 (255)
    )
;



COMMENT ON COLUMN Water_Body.Name IS 'Gewaesserkennziffer (GKZ)'
;
CREATE UNIQUE INDEX "Water_Body Name UKX" ON Water_Body
    (
     Name ASC
    )
;
CREATE UNIQUE INDEX "Water_Body PKX" ON Water_Body
    (
     ID ASC
    )
;

ALTER TABLE Water_Body
    ADD CONSTRAINT "Water_Body PK" PRIMARY KEY ( ID ) ;

ALTER TABLE Water_Body
    ADD CONSTRAINT "Water_Body Name UK" UNIQUE ( Name ) ;


CREATE TABLE Waterlevel_Fixation
    (
     ID NUMBER (20)  NOT NULL ,
     Station NUMBER (8,1)  NOT NULL ,
     Location MDSYS.SDO_GEOMETRY ,
     Creation_Date TIMESTAMP (0)  NOT NULL ,
     Editing_Date TIMESTAMP (0)  NOT NULL ,
     Editing_User VARCHAR2 (50)  NOT NULL ,
     Measurement_Date TIMESTAMP (0) ,
     Waterlevel NUMBER (8,3) ,
     Discharge NUMBER (8,3) ,
     Description VARCHAR2 (255) ,
     Event NUMBER (20)  NOT NULL
    )
;


CREATE UNIQUE INDEX "Waterlevel_Fixation PKX" ON Waterlevel_Fixation
    (
     ID ASC
    )
;
CREATE INDEX Event__Waterlevel_FixationX ON Waterlevel_Fixation
    (
     Event ASC
    )
;

ALTER TABLE Waterlevel_Fixation
    ADD CONSTRAINT "Waterlevel_Fixation PK" PRIMARY KEY ( ID ) ;



ALTER TABLE Point
    ADD CONSTRAINT CS_Part__Point FOREIGN KEY
    (
     Cross_Section_Part
    )
    REFERENCES Cross_Section_Part
    (
     ID
    )
    ON DELETE CASCADE
;


ALTER TABLE Cross_Section_Part
    ADD CONSTRAINT CS__CS_Part FOREIGN KEY
    (
     Cross_Section
    )
    REFERENCES Cross_Section
    (
     ID
    )
    ON DELETE CASCADE
;


ALTER TABLE Waterlevel_Fixation
    ADD CONSTRAINT Event__Waterlevel_Fixation FOREIGN KEY
    (
     Event
    )
    REFERENCES Event
    (
     ID
    )
    ON DELETE CASCADE
;


ALTER TABLE Roughness
    ADD CONSTRAINT Point_Kind__Roughness FOREIGN KEY
    (
     Point_Kind
    )
    REFERENCES Point_Kind
    (
     Name
    )
    ON DELETE CASCADE
;


ALTER TABLE Vegetation
    ADD CONSTRAINT Point_Kind__Vegetation FOREIGN KEY
    (
     Point_Kind
    )
    REFERENCES Point_Kind
    (
     Name
    )
    ON DELETE CASCADE
;


ALTER TABLE Point
    ADD CONSTRAINT Roughness__Point FOREIGN KEY
    (
     Roughness_Point_Kind,
     Roughness
    )
    REFERENCES Roughness
    (
     Point_Kind,
     Name
    )
    ON DELETE SET NULL
;


ALTER TABLE Cross_Section
    ADD CONSTRAINT State__CS FOREIGN KEY
    (
     State
    )
    REFERENCES State
    (
     ID
    )
    ON DELETE CASCADE
;


ALTER TABLE Point
    ADD CONSTRAINT Vegetation__Point FOREIGN KEY
    (
     Vegetation_Point_Kind,
     Vegetation
    )
    REFERENCES Vegetation
    (
     Point_Kind,
     Name
    )
    ON DELETE SET NULL
;


ALTER TABLE Cross_Section
    ADD CONSTRAINT Water_Body__CS FOREIGN KEY
    (
     Water_Body
    )
    REFERENCES Water_Body
    (
     ID
    )
    ON DELETE CASCADE
;


ALTER TABLE Event
    ADD CONSTRAINT Water_Body__Event FOREIGN KEY
    (
     Water_Body
    )
    REFERENCES Water_Body
    (
     ID
    )
    ON DELETE CASCADE
;














-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            11
-- CREATE INDEX                            26
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- ERRORS                                   0
-- WARNINGS                                 0

-- 04_create_sequence

create sequence "SEQ_PDB"
start with 1
increment by 1
nocache
nocycle
noorder
;

-- 05_register_geometries

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)
VALUES('POINT','LOCATION',
MDSYS.SDO_DIM_ARRAY
(MDSYS.SDO_DIM_ELEMENT('${srsXName}',${srsMinX},${srsMaxX},${srsTolX}),
MDSYS.SDO_DIM_ELEMENT('${srsYName}',${srsMinY},${srsMaxY},${srsTolY}),
MDSYS.SDO_DIM_ELEMENT('${srsZName}',${srsMinZ},${srsMaxZ},${srsTolZ})
), ${SRID}
);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)
VALUES('CROSS_SECTION_PART','LINE',
MDSYS.SDO_DIM_ARRAY
(MDSYS.SDO_DIM_ELEMENT('${srsXName}',${srsMinX},${srsMaxX},${srsTolX}),
MDSYS.SDO_DIM_ELEMENT('${srsYName}',${srsMinY},${srsMaxY},${srsTolY}),
MDSYS.SDO_DIM_ELEMENT('${srsZName}',${srsMinZ},${srsMaxZ},${srsTolZ})
), ${SRID}
);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)
VALUES('CROSS_SECTION','LINE',
MDSYS.SDO_DIM_ARRAY
(MDSYS.SDO_DIM_ELEMENT('${srsXName}',${srsMinX},${srsMaxX},${srsTolX}),
MDSYS.SDO_DIM_ELEMENT('${srsYName}',${srsMinY},${srsMaxY},${srsTolY}),
MDSYS.SDO_DIM_ELEMENT('${srsZName}',${srsMinZ},${srsMaxZ},${srsTolZ})
), ${SRID}
);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)
VALUES('WATER_BODY','RIVERLINE',
MDSYS.SDO_DIM_ARRAY
(MDSYS.SDO_DIM_ELEMENT('${srsXName}',${srsMinX},${srsMaxX},${srsTolX}),
MDSYS.SDO_DIM_ELEMENT('${srsYName}',${srsMinY},${srsMaxY},${srsTolY}),
MDSYS.SDO_DIM_ELEMENT('${srsZName}',${srsMinZ},${srsMaxZ},${srsTolZ})
), ${SRID}
);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)
VALUES('WATERLEVEL_FIXATION','LOCATION',
MDSYS.SDO_DIM_ARRAY
(MDSYS.SDO_DIM_ELEMENT('${srsXName}',${srsMinX},${srsMaxX},${srsTolX}),
MDSYS.SDO_DIM_ELEMENT('${srsYName}',${srsMinY},${srsMaxY},${srsTolY}),
MDSYS.SDO_DIM_ELEMENT('${srsZName}',${srsMinZ},${srsMaxZ},${srsTolZ})
), ${SRID}
);


-- 06_prefill_table_info

INSERT INTO INFO("KEY", "VALUE") VALUES ('SRID', '${SRID}');
-- 07_prefill_table__point_kind
INSERT INTO point_kind (name, label, description) VALUES ('GAF', 'GAF', 'GAF');

-- 08_prefill_table__roughness
INSERT INTO roughness (name, label, description, point_kind) VALUES ('-1', 'unknown', 'unknown','GAF');

INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('1', 'glatt', 'glatt', 'GAF',0.001, 80);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('2', 'Feinsand, Schlamm', 'Feinsand, Schlamm', 'GAF',0.03, 55);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('3', 'Sand oder Feinkies', 'Sand oder Feinkies', 'GAF',0.05, 53);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('4', 'Feinkies', 'Feinkies', 'GAF',0.05, 50);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('5', 'mittlerer Kies', 'mittlerer Kies', 'GAF',0.08, 40);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('6', 'Schotter, mittlerer Grobkies, verkrautete Erdkanäle', 'Schotter, mittlerer Grobkies, verkrautete Erdkanäle', 'GAF',0.082, 35);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('7', 'Lehm, Wasserpflanzen', 'Lehm, Wasserpflanzen', 'GAF',0.1, 33);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('8', 'Steinschüttung,stark geschiebeführender Fluss,Wurzeln', 'Steinschüttung,stark geschiebeführender Fluss,Wurzeln', 'GAF',0.15, 30);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('9', 'Kiesanlandung, Wurzelgeflecht', 'Kiesanlandung, Wurzelgeflecht', 'GAF',0.2, 28);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('10', 'grobe Steine, Geröllanlandung', 'grobe Steine, Geröllanlandung', 'GAF',0.3, 25);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('11', 'Gebirgsflüsse mit grobem Geröll, verkrautete Erdkanäle', 'Gebirgsflüsse mit grobem Geröll, verkrautete Erdkanäle', 'GAF',0.45, 22.5);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('12', 'Fels', 'Fels', 'GAF',0.6, 20);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('13', 'Wildbach', 'Wildbach', 'GAF',0.9, 15);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('14', 'Wildbach mit starkem Geschiebetrieb, roher Felsausbruch', 'Wildbach mit starkem Geschiebetrieb, roher Felsausbruch', 'GAF',2, 12);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('20', 'Stahl, Zementputz geglättet, Beton aus Vakuumschalung', 'Stahl, Zementputz geglättet, Beton aus Vakuumschalung', 'GAF',0.001, 95);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('21', 'Holz, ungehobelt', 'Holz, ungehobelt', 'GAF',0.002, 90);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('22', 'Beton, glatt, Asphaltbeton, Klinker, sorgfältig verfugt', 'Beton, glatt, Asphaltbeton, Klinker, sorgfältig verfugt', 'GAF',0.003, 75);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('23', 'Ziegelmauerwerk, Rauputz, Verbundpflaster', 'Ziegelmauerwerk, Rauputz, Verbundpflaster', 'GAF',0.005, 70);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('24', 'Beton rauh, glatte Bruchsteine', 'Beton rauh, glatte Bruchsteine', 'GAF',0.015, 60);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('25', 'Pflaster, ARMCO-Profile', 'Pflaster, ARMCO-Profile', 'GAF',0.04, 50);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('26', 'Beton mit Fugen, grobes Bruchsteinmauerwerk', 'Beton mit Fugen, grobes Bruchsteinmauerwerk', 'GAF',0.02, 48);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('27', 'Natursteine, rauh', 'Natursteine, rauh', 'GAF',0.09, 40);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('28', 'Spundwände', 'Spundwände', 'GAF',0.06, 35);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('29', 'Schotter, Steinschüttung, Rasengittersteine', 'Schotter, Steinschüttung, Rasengittersteine', 'GAF',0.2, 30);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('30', 'grobe Steinschüttung', 'grobe Steinschüttung', 'GAF',0.4, 25);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('31', 'Steinschüttung mit Krautbewuchs', 'Steinschüttung mit Krautbewuchs', 'GAF',0.5, 23.5);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('32', 'Rauhe Sohlrampe', 'Rauhe Sohlrampe', 'GAF',1.5, 15);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('50', 'Rasen', 'Rasen', 'GAF',0.06, 40);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('51', 'Gras, Acker ohne Bewuchs', 'Gras, Acker ohne Bewuchs', 'GAF',0.2, 30);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('52', 'Waldboden', 'Waldboden', 'GAF',0.24, 27);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('53', 'Wiese, felsiger Waldboden', 'Wiese, felsiger Waldboden', 'GAF',0.25, 25);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('54', 'Gras mit Stauden', 'Gras mit Stauden', 'GAF',0.3, 24);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('55', 'Krautiger Bewuchs', 'Krautiger Bewuchs', 'GAF',0.4, 22);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('56', 'Acker mit Kulturen', 'Acker mit Kulturen', 'GAF',0.6, 21);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('57', 'unregelmäßiges Vorland', 'unregelmäßiges Vorland', 'GAF',0.8, 15);
INSERT INTO roughness (name, label, description, point_kind, k_value, kst_value) VALUES ('58', 'sehr unregelmäßiges Vorland mit Verbauungen', 'sehr unregelmäßiges Vorland mit Verbauungen', 'GAF',1, 12);

-- 09_prefill_table__vegetation
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('-1', 'unknown', 'unknown','GAF',0,0,0);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('1', 'Röhricht, licht', 'Röhricht, licht', 'GAF',0.003, 0.03, 0.03);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('2', 'Röhricht, dicht', 'Röhricht, dicht', 'GAF',0.005, 0.02, 0.02);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('3', 'Sträucher, licht', 'Sträucher, licht', 'GAF',0.03, 0.35, 0.35);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('4', 'Sträucher, mittel', 'Sträucher, mittel', 'GAF',0.045, 0.25, 0.25);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('5', 'Sträucher, dicht', 'Sträucher, dicht', 'GAF',0.06, 0.15, 0.15);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('6', 'Bäume, licht', 'Bäume, licht', 'GAF',0.05, 5, 5);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('7', 'Bäume, mittel', 'Bäume, mittel', 'GAF',0.2, 10, 10);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('8', 'Bäume, dicht', 'Bäume, dicht', 'GAF',1, 5, 5);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('11', 'Büsche, einjährig', 'Büsche, einjährig', 'GAF',0.5, 10, 10);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('12', 'Büsche, mehrjährig', 'Büsche, mehrjährig', 'GAF',3.5, 10, 10);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('13', 'Bäume, einjährig', 'Bäume, einjährig', 'GAF',0.05, 20, 20);
INSERT INTO vegetation(name, label, description, point_kind, dp, ax, ay) VALUES ('14', 'Bäume, mehrjährig', 'Bäume, mehrjährig', 'GAF',1, 20, 20);
 
-- 99_create_spatial_indexes.sql

CREATE INDEX IX_POINT__LOCATION ON "POINT"("LOCATION") INDEXTYPE IS MDSYS.SPATIAL_INDEX ;
CREATE INDEX IX_CROSS_SECTION_PART__LINE ON CROSS_SECTION_PART(LINE) INDEXTYPE IS MDSYS.SPATIAL_INDEX ;
CREATE INDEX IX_CROSS_SECTION__LINE ON CROSS_SECTION(LINE) INDEXTYPE IS MDSYS.SPATIAL_INDEX ;
CREATE INDEX IX_WATER_BODY__RIVERLINE ON WATER_BODY(RIVERLINE) INDEXTYPE IS MDSYS.SPATIAL_INDEX ;
CREATE INDEX IX_WL_FIX__LOCATION ON WATERLEVEL_FIXATION(LOCATION) INDEXTYPE IS MDSYS.SPATIAL_INDEX ;

-- Version endgültig setzen
UPDATE INFO set value='0.0.1'  where key ='Version';
commit;

-- update to V0.0.2
-- Version setzen auf "creating" oder "updateing"
UPDATE INFO set value='updateing 0.0.1 to 0.0.2'  where key ='Version';

-- 03_create_tables

-- Generated by Oracle SQL Developer Data Modeler 3.0.0.665
--   at:        2011-07-13 16:56:15 MESZ
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g


CREATE TABLE Document
    (
     ID NUMBER (20)  NOT NULL ,
     Name VARCHAR2 (100)  NOT NULL ,
     Location MDSYS.SDO_GEOMETRY ,
     FileName VARCHAR2 (2048)  NOT NULL , 
     MimeType VARCHAR2 (50) ,
     Creation_Date TIMESTAMP (0)  NOT NULL , 
     Editing_Date TIMESTAMP (0)  NOT NULL , 
     Editing_User VARCHAR2 (50)  NOT NULL , 
     Measurement_Date TIMESTAMP (0) , 

--  [°] - Aufnahmerichtung (0-360)
 ShotDirection NUMBER (8,3) CHECK ( ShotDirection BETWEEN 0 AND 360) ,

--  [°] - Öffnungswinkel (0-360)
 ViewAngle NUMBER (8,3) CHECK ( ViewAngle BETWEEN 0 AND 360) ,
     Description VARCHAR2 (255) , 
     Cross_Section_ID NUMBER (20) ,
     Water_Body_ID NUMBER (20) ,
     State_ID NUMBER (20)
    ) 
;



COMMENT ON COLUMN Document.ShotDirection IS '[°] - Aufnahmerichtung (0-360)'
;

COMMENT ON COLUMN Document.ViewAngle IS '[°] - Öffnungswinkel (0-360)'
;

ALTER TABLE Document
    ADD CONSTRAINT "Document PK" PRIMARY KEY ( ID  ) ;

ALTER TABLE Document 
    ADD CONSTRAINT "Document Name UK" UNIQUE ( FileName ) ;


COMMENT ON COLUMN Cross_Section.Station IS '[m]'
;


COMMENT ON COLUMN Event.Type IS 'Art des Ereignisses: Messung, Simulation'
;


COMMENT ON COLUMN Point.Code IS '(GAF-) Kennzeichnung'
;


COMMENT ON COLUMN Point.Width IS '[m]'
;


COMMENT ON COLUMN Point.Height IS '[m NN]'
;


COMMENT ON COLUMN Point.Roughness_K_Value IS '[m]'
;


COMMENT ON COLUMN Point.Roughness_Kst_Value IS '[m^.33/s]'
;


COMMENT ON COLUMN Point.Vegetation_Dp IS '[m]'
;


COMMENT ON COLUMN Point.Vegetation_Ax IS '[m]'
;


COMMENT ON COLUMN Point.Vegetation_Ay IS '[m]'
;


COMMENT ON COLUMN Point_Kind.Name IS 'Quelle für Import: GAF, WPROF, ...'
;


COMMENT ON COLUMN Roughness.K_Value IS '[m]'
;


COMMENT ON COLUMN Roughness.Kst_Value IS '[m^.33/s]'
;


COMMENT ON COLUMN Roughness.Source IS 'Angabe einer Literaturstelle'
;


COMMENT ON COLUMN State.IsStateZero IS 'Handelt es sich bei diesem Zustand um einen Ur-Zustand (d.h. einen Erstimport)?'
;


COMMENT ON COLUMN State.Source IS 'data source (e.g. file name)'
;


COMMENT ON COLUMN Vegetation.Dp IS '[m]'
;


COMMENT ON COLUMN Vegetation.Ax IS '[m]'
;


COMMENT ON COLUMN Vegetation.Ay IS '[m]'
;


COMMENT ON COLUMN Vegetation.Source IS 'Angabe einer Literaturstelle'
;


COMMENT ON COLUMN Water_Body.Rank IS 'Gewässerordnung (ggf. zur Darstellung)'
;


COMMENT ON COLUMN Waterlevel_Fixation.Station IS '[m]'
;


COMMENT ON COLUMN Waterlevel_Fixation.Waterlevel IS '[m NN]'
;


COMMENT ON COLUMN Waterlevel_Fixation.Discharge IS '[m³/s]'
;


ALTER TABLE Event DROP CONSTRAINT "Event Name UK" CASCADE
;

DROP INDEX "Event Name UKX"
;

CREATE UNIQUE INDEX "Event Name UKX" ON Event
    (
     Name,
     Water_Body ASC
    )
;

ALTER TABLE Event ADD
    CONSTRAINT "Event Name UK" UNIQUE (
    Name ,
     Water_Body
    ) ;



ALTER TABLE Document
    ADD CONSTRAINT CS_Document FOREIGN KEY
    (
     Cross_Section_ID
    )
    REFERENCES Cross_Section
    (
     ID
    )
    ON DELETE SET NULL
    NOT DEFERRABLE
;


ALTER TABLE Document
    ADD CONSTRAINT State_Document FOREIGN KEY
    (
     State_ID
    )
    REFERENCES State
    (
     ID
    )
    ON DELETE SET NULL
    NOT DEFERRABLE
;


ALTER TABLE Document
    ADD CONSTRAINT WB_Document FOREIGN KEY
    (
     Water_Body_ID
    )
    REFERENCES Water_Body
    (
     ID
    )
    ON DELETE SET NULL
    NOT DEFERRABLE
;


-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                             1
-- CREATE INDEX                             0
-- CREATE VIEW                              0
-- ALTER TABLE                              8
-- DROP TABLE                               0
-- DROP INDEX                               0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- ALTER SEQUENCE                           0
-- ALTER MATERIALIZED VIEW                  0
-- DROP VIEW                                0

--
-- ERRORS                                   0
-- WARNINGS                                 0

-- 05_register_geometries
INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)
VALUES('DOCUMENT','LOCATION',
MDSYS.SDO_DIM_ARRAY
(MDSYS.SDO_DIM_ELEMENT('${srsXName}',${srsMinX},${srsMaxX},${srsTolX}),
MDSYS.SDO_DIM_ELEMENT('${srsYName}',${srsMinY},${srsMaxY},${srsTolY}),
MDSYS.SDO_DIM_ELEMENT('${srsZName}',${srsMinZ},${srsMaxZ},${srsTolZ})
), ${SRID}
);

-- 06_prefill_table_info
INSERT INTO INFO("KEY", "VALUE") VALUES ('DocumentServer', '${DocumentServer}');

-- 99_create_spatial_indexes
CREATE INDEX IX_DOCUMENT__LOCATION ON "DOCUMENT"("LOCATION") INDEXTYPE IS MDSYS.SPATIAL_INDEX ;
-- Version endgültig setzen
UPDATE INFO set value='0.0.3'  where key ='Version';
commit;


-- Version 0.0.3
-- Version setzen auf "creating" oder "updateing"
UPDATE INFO set value='updateing 0.0.2 to 0.0.3'  where key ='Version';

GRANT SELECT ON CROSS_SECTION TO PDB_USER;
GRANT SELECT ON CROSS_SECTION_PART TO PDB_USER;
GRANT SELECT ON EVENT TO PDB_USER;
GRANT SELECT ON INFO TO PDB_USER;
GRANT SELECT ON POINT TO PDB_USER;
GRANT SELECT ON POINT_KIND TO PDB_USER;
GRANT SELECT ON ROUGHNESS TO PDB_USER;
GRANT SELECT ON STATE TO PDB_USER;
GRANT SELECT ON VEGETATION TO PDB_USER;
GRANT SELECT ON WATERLEVEL_FIXATION TO PDB_USER;
GRANT SELECT ON WATER_BODY TO PDB_USER;
GRANT SELECT ON DOCUMENT TO PDB_USER;


GRANT DELETE, INSERT, SELECT, UPDATE ON CROSS_SECTION TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON CROSS_SECTION_PART TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVENT TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON INFO TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON POINT TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON POINT_KIND TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON ROUGHNESS TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON STATE TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON VEGETATION TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON WATERLEVEL_FIXATION TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON WATER_BODY TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOCUMENT TO PDB_ADMIN;

GRANT SELECT ON SEQ_PDB TO PDB_ADMIN;


INSERT INTO INFO("KEY", "VALUE") VALUES ('srsXName', '${srsXName}');
INSERT INTO INFO("KEY", "VALUE") VALUES ('srsMinX', '${srsMinX}');
INSERT INTO INFO("KEY", "VALUE") VALUES ('srsMaxX', '${srsMaxX}');
INSERT INTO INFO("KEY", "VALUE") VALUES ('srsTolX', '${srsTolX}');

INSERT INTO INFO("KEY", "VALUE") VALUES ('srsYName', '${srsYName}');
INSERT INTO INFO("KEY", "VALUE") VALUES ('srsMinY', '${srsMinY}');
INSERT INTO INFO("KEY", "VALUE") VALUES ('srsMaxY', '${srsMaxY}');
INSERT INTO INFO("KEY", "VALUE") VALUES ('srsTolY', '${srsTolY}');

INSERT INTO INFO("KEY", "VALUE") VALUES ('srsZName', '${srsZName}');
INSERT INTO INFO("KEY", "VALUE") VALUES ('srsMinZ', '${srsMinZ}');
INSERT INTO INFO("KEY", "VALUE") VALUES ('srsMaxZ', '${srsMaxZ}');
INSERT INTO INFO("KEY", "VALUE") VALUES ('srsTolZ', '${srsTolZ}');

-- Version endgültig setzen
UPDATE INFO set value='0.0.3'  where key ='Version';
commit;

-- Version setzen auf "creating" oder "updateing"
UPDATE INFO set value='updating 0.0.3 to 0.0.4'  where key ='Version';

-- 
ALTER TABLE Document DROP CONSTRAINT "Document Name UK" CASCADE;
ALTER TABLE DOCUMENT DROP CONSTRAINT CS_DOCUMENT CASCADE;
ALTER TABLE DOCUMENT ADD
(
  CONSTRAINT CS_DOCUMENT 
  FOREIGN KEY( CROSS_SECTION_ID)
  REFERENCES CROSS_SECTION( ID)
  ON DELETE CASCADE 
  NOT DEFERRABLE
  ENABLE
);


ALTER TABLE DOCUMENT DROP CONSTRAINT STATE_DOCUMENT CASCADE;
ALTER TABLE DOCUMENT ADD
(
  CONSTRAINT STATE_DOCUMENT 
  FOREIGN KEY( STATE_ID)
  REFERENCES STATE( ID)
  ON DELETE CASCADE 
  NOT DEFERRABLE
  ENABLE
);

ALTER TABLE DOCUMENT DROP CONSTRAINT WB_DOCUMENT CASCADE;
ALTER TABLE DOCUMENT ADD
(
  CONSTRAINT WB_DOCUMENT 
  FOREIGN KEY( WATER_BODY_ID)
  REFERENCES WATER_BODY( ID)
  ON DELETE CASCADE 
  NOT DEFERRABLE
  ENABLE
);

ALTER TABLE Point ADD( Roughness_Factor NUMBER (8,5) NULL );
COMMENT ON COLUMN Point.Roughness_Factor IS 'factor to apply to roughness value';

ALTER TABLE Roughness ADD( Color VARCHAR2(10) NULL );
COMMENT ON COLUMN Roughness.Color IS 'color (hex)';

ALTER TABLE Vegetation ADD( Color VARCHAR2(10) NULL );
COMMENT ON COLUMN Vegetation.Color IS 'color (hex)';

-- Daten

-- update tables roughness and vegetation to overcome encoding problems
 update roughness set label='Schotter, mittlerer Grobkies, verkrautete Erdkanäle', description='Schotter, mittlerer Grobkies, verkrautete Erdkanäle' where name ='6';
 update roughness set label='Steinschüttung, stark geschiebeführender Fluss, Wurzeln', description='Steinschüttung, stark geschiebeführender Fluss, Wurzeln' where name ='8';
 update roughness set label='grobe Steine, Geröllanlandung', description='grobe Steine, Geröllanlandung' where name ='10';
 update roughness set label='Gebirgsflüsse mit grobem Geröll, verkrautete Erdkanäle', description='Gebirgsflüsse mit grobem Geröll, verkrautete Erdkanäle' where name ='11';
 update roughness set label='Spundwände', description='Spundwände' where name ='28';
 update roughness set label='Schotter, Steinschüttung, Rasengittersteine', description='Schotter, Steinschüttung, Rasengittersteine' where name ='29';
 update roughness set label='grobe Steinschüttung', description='grobe Steinschüttung', point_kind='GAF' where name ='30';
 update roughness set label='Steinschüttung mit Krautbewuchs', description='Steinschüttung mit Krautbewuchs' where name ='31';
 update roughness set label='unregelmäßiges Vorland', description='unregelmäßiges Vorland' where name ='57';
 update roughness set label='sehr unregelmäßiges Vorland mit Verbauungen', description='sehr unregelmäßiges Vorland mit Verbauungen' where name ='58';


-- 09_prefill_table__vegetation
 update vegetation set label= 'Röhricht, licht', description='Röhricht, licht' where name ='1';
 update vegetation set label= 'Röhricht, dicht', description='Röhricht, dicht' where name ='2';
 update vegetation set label= 'Sträucher, licht', description='Sträucher, licht' where name ='3';
 update vegetation set label= 'Sträucher, mittel', description='Sträucher, mittel' where name ='4';
 update vegetation set label= 'Sträucher, dicht', description='Sträucher, dicht' where name ='5';
 update vegetation set label= 'Bäume, licht', description='Bäume, licht' where name ='6';
 update vegetation set label= 'Bäume, mittel', description='Bäume, mittel' where name ='7';
 update vegetation set label= 'Bäume, dicht', description='Bäume, dicht' where name ='8';
 update vegetation set label= 'Büsche, einjährig', description='Büsche, einjährig' where name ='11';
 update vegetation set label= 'Büsche, mehrjährig', description='Büsche, mehrjährig' where name ='12';
 update vegetation set label= 'Bäume, einjährig', description='Bäume, einjährig' where name ='13';
 update vegetation set label= 'Bäume, mehrjährig', description='Bäume, mehrjährig' where name ='14';


-- set default colors for vegetation and roughness
update vegetation set color='#FF0000' where name ='-1';
update vegetation set color='#00FFFF' where name ='1';
update vegetation set color='#00CED1' where name ='2';
update vegetation set color='#FFE1FF' where name ='3';
update vegetation set color='#EE7AE9' where name ='4';
update vegetation set color='#B452CD' where name ='5';
update vegetation set color='#8FBC8F' where name ='6';
update vegetation set color='#3CB357' where name ='7';
update vegetation set color='#006400' where name ='8';
update vegetation set color='#7CFC00' where name ='11';
update vegetation set color='#00CD00' where name ='12';
update vegetation set color='#CCCC00' where name ='13';
update vegetation set color='#999900' where name ='14';

-- natürl. Gewässer
update roughness set color='#FF0000' where name ='-1';
update roughness set color='#FFB90F' where name ='1';
update roughness set color='#FF8247' where name ='2';
update roughness set color='#EEE685' where name ='3';
update roughness set color='#EEEE00' where name ='4';
update roughness set color='#EEAD0E' where name ='5';
update roughness set color='#EE7942' where name ='6';
update roughness set color='#CDC673' where name ='7';
update roughness set color='#CDCD00' where name ='8';
update roughness set color='#CD950C' where name ='9';
update roughness set color='#CD6839' where name ='10';
update roughness set color='#8B864E' where name ='11';
update roughness set color='#8B8B00' where name ='12';
update roughness set color='#8B670B' where name ='13';
update roughness set color='#8B4726' where name ='14';
-- 
update roughness set color='#FCFCFC' where name ='20';
update roughness set color='#EAEAEA' where name ='21';
update roughness set color='#D8D8D8' where name ='22';
update roughness set color='#C6C6C6' where name ='23';
update roughness set color='#B4B4B4' where name ='24';
update roughness set color='#A2A2A2' where name ='25';
update roughness set color='#909090' where name ='26';
update roughness set color='#7E7E7E' where name ='27';
update roughness set color='#6C6C6C' where name ='28';
update roughness set color='#5A5A5A' where name ='29';
update roughness set color='#484848' where name ='30';
update roughness set color='#363636' where name ='31';
update roughness set color='#242424' where name ='32';
-- Vorländer
update roughness set color='#CCFF99' where name ='50';
update roughness set color='#98FB98' where name ='51';
update roughness set color='#00FF7F' where name ='52';
update roughness set color='#7FFF00' where name ='53';
update roughness set color='#32CD32' where name ='54';
update roughness set color='#00FA9A' where name ='55';
update roughness set color='#9ACD32' where name ='56';
update roughness set color='#228B22' where name ='57';
update roughness set color='#006400' where name ='58';


-- Version endgültig setzen
UPDATE INFO set value='0.0.4'  where key ='Version';
commit;