/* Datenreihen:
/* <Nr>- <Dateiname> <sichtbar:J,N> <Diagrammtyp:L,B,P,M> <y-Achse:1,2> <Titel> [<Blocknummer>] 

DFormat: 0


Extend1: -1.000000 -104999.000000 1.000000 94999.050000 0.200000 13334.000000
Extend2: -1.000000 -999999.000000 1.000000 999999.000000 0.200000 133334.000000
Gitternetz: J
dYautom: J
Linientyp_const: N
dTmin: 60
Balkenbreite: 0
xAchse1: -1 1   /* 1. Zeile  <Formate:0-11 (autom.=-1)> <doppelt unterdrücken J=1/N=0>
xAchse2: -1 1   /* 2. Zeile

/* Alle Einstellungen sind optional, also nicht zwingend.
/* Weitere zusätzliche Optionen, die nur von außerhalb eingestellt werden können:
/*   AnfDatum: Anfangszeitpunkt des darzustellenden Bereiches
/*   EndDatum: Endzeitpunkt des darzustellenden Bereiches
/*   mT0:      Anfangszeitpunkt (TT.MM.JJJJ hh:mm) für x-Achsenbeschriftung
