//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Plotter.rc
//
#define IDS_ERROR_READFILE              17
#define IDS_LSECTION_DESC1              18
#define IDS_STATION_DESC1               19
#define IDS_XVALUE                      20
#define IDS_YVALUE                      21
#define IDS_PROFIL                      22
#define IDS_STATIONIERUNG               23
#define IDS_TABLE                       24
#define IDS_STAMP                       25
#define IDS_FRAME                       26
#define IDS_DATA                        27
#define IDS_PROFIL_PLURAL               28
#define IDS_STATION_DESC2               29
#define IDS_NONE                        30
#define IDS_OPTIONS                     31
#define IDS_PROPERTIES                  32
#define IDS_TITLE                       33
#define IDS_STPL_AG1                    34
#define IDS_STPL_AG2                    35
#define IDS_STPL_PB1                    36
#define IDS_STPL_PB2                    37
#define IDS_STPL_PB3                    38
#define IDS_STPL_BB1                    39
#define IDS_STPL_BB2                    40
#define IDS_STPL_BB3                    41
#define IDS_STPL_PN                     42
#define IDS_STPL_DAT                    43
#define IDS_STPL_BN                     44
#define IDS_GRAPHIC_ATTRIB              45
#define IDS_CLOSE                       46
#define IDP_OLE_INIT_FAILED             47
#define IDP_FAILED_TO_CREATE            48
#define IDS_OPENTREE_TIP                49
#define IDS_LOADFAILED                  49
#define IDS_STPL_MS                     50
#define IDS_MARGINS_TOP                 51
#define IDS_MARGINS_LEFT                52
#define IDS_MARGINS_RIGHT               53
#define IDS_ORIGINFILE                  54
#define IDS_MARGINS_BOTTOM              55
#define IDS_MARGINS_DIST                56
#define IDS_MARGINS_HINT                57
#define IDS_HEIGHT                      58
#define IDS_DELETE                      59
#define IDS_CREATING_DRAWING            60
#define IDS_FORMATTING_DRAWING          61
#define IDS_RENEWING_OBJECTS            62
#define IDS_EXTRATEXT                   63
#define IDS_STPL_UD                     64
#define IDS_ERROR_DDECOMMAND            65
#define IDS_AUTOMATIC                   66
#define IDS_NEWSTEMPEL                  67
#define IDS_INVALIDRANGE                68
#define IDS_FILLING                     69
#define IDS_RENEWING_TEMPLATE           70
#define IDS_RENEWING_DRAWING            71
#define IDS_UNKNOWN                     72
#define IDS_DOC_PROPS                   73
#define IDS_DEFAULT_HEIGHT              74
#define IDS_STATE_DLG_TITLE             75
#define IDS_GPAGE__STATIC_SCALE         75
#define IDS_GPAGE_STATIC_SCALE          75
#define IDS_DEFAULT_TITLE               76
#define IDS_FMT_BEZUGSHOEHE             77
#define IDS_FMT_GEWAESSER               78
#define IDS_FMT_ZUSTAND                 79
#define IDS_FMT_STATION                 80
#define IDS_FMT_ANFANG                  81
#define IDS_FMT_ENDE                    82
#define IDS_FMT_URDATEI                 83
#define IDS_FMT_VZK                     84
#define IDS_FMT_PK                      85
#define IDS_FMT_NAME                    86
#define IDS_DEFAULT_CTITLE              87
#define IDS_DEFAULT_LTITLE              88
#define IDS_CROSSSECTION                89
#define IDS_LENGTHSECTION               90
#define IDS_MARGINS_PROFIL              91
#define IDS_MARGINS_STEMPEL             92
#define IDS_STPL_ZU                     93
#define IDS_CLOSEWITHSAVE               94
#define IDS_VERSION                     95
#define IDS_WARN_LARGEBEZUG             96
#define IDS_PROFILE_OVERVIEW_TITLE      97
#define IDS_LEGENDE                     98
#define IDS_PROFIL_OV_XY_TITLE          99
#define IDR_MAINFRAME                   100
#define IDR_PLOTTERTYPE                 101
#define IDR_PLOTTERTYPE_SRVR_IP         102
#define IDS_PROFIL_OV_XY_HEIGHT         102
#define IDD_PROP_TYPE                   102
#define IDS_EMPTY                       103
#define IDR_PLOTTERTYPE_SRVR_EMB        104
#define IDS_PROFIL_OV_XY_WIDTH          104
#define IDS_PHYSICAL_MEM                105
#define IDR_PLOTTERTYPE_CNTR_IP         106
#define IDS_TITLECOMMENT                106
#define IDS_DISK_SPACE                  107
#define IDD_SUMM_PAGE                   108
#define IDS_DEFAULT_COMMENT             108
#define CG_IDR_POPUP_CHILD_FRAME        109
#define IDS_FMT_COMMENT                 109
#define ID_MULTI_PREVIEW_UPDATE         109
#define IDS_DISK_SPACE_UNAVAIL          110
#define IDC_AUTHOR                      111
#define IDS_ABOUT_TITLE                 111
#define IDR_PLOTTERTYPE_DEBUG           112
#define IDC_KEYWORDS                    113
#define IDR_PROFDATTYPE_DEBUG           113
#define IDS_CANT_SHOW_FILLING           114
#define IDC_COMMENTS                    115
#define IDR_PROFDATTYPE                 115
#define IDC_TITLE                       116
#define IDS_UNKNOWN_SCALE               116
#define IDC_SUBJECT                     117
#define IDS_KNOWN_SCALE                 117
#define IDC_SAVEDBY                     118
#define IDS_UNKNOWN_MINMAX              118
#define IDC_REVNUM                      119
#define IDS_KNOWN_MINMAX                119
#define IDC_EDITTIME                    120
#define IDS_UNKNOWN_RECMAX              120
#define IDS_GPAGE_HINT                  120
#define IDC_LASTPRINT                   121
#define IDS_KNOWN_RECMAX                121
#define IDS_GPAGE_HEIGHT_DEFAULT        121
#define IDC_CREATEDATE                  122
#define IDS_HOCHWERT                    122
#define IDC_LASTSAVE                    123
#define IDS_RECHTSWERT                  123
#define IDC_NUMPAGES                    124
#define IDS_GRID                        124
#define IDC_NUMWORDS                    125
#define IDS_MAINTOOLBAR                 125
#define IDC_NUMCHARS                    126
#define IDS_DRAWTOOLBAR                 126
#define IDC_APPNAME                     127
#define IDS_MARGINS_TITLE               127
#define IDC_SECURITY                    128
#define IDS_IS_PROMILLE                 128
#define IDS_GRADIENT                    129
#define IDS_HEIGHTM                     130
#define IDS_DXFFILES_ALLFILES           131
#define IDS_USER                        132
#define IDS_SETTING                     133
#define IDS_PROPS_N                     134
#define IDS_MARGINS_STEMPEL_ALIGN       135
#define IDS_MARGINS_MARGINS             136
#define IDS_PHYSICAL_MEM_TEXT           137
#define IDS_DISK_SPACE_TEXT             138
#define IDS_LICENCE_TEXT                139
#define IDS_MARGINS_ALIGN               140
#define IDS_MARGINS_ALIGN_NW            141
#define IDS_MARGINS_ALIGN_NE            142
#define IDS_MARGINS_ALIGN_SW            143
#define IDS_MARGINS_ALIGN_SE            144
#define IDS_MARGINS_STAMPSCALE          145
#define IDS_GPAGE_STATIC_X_SCALE        146
#define IDS_GPAGE_STATIC_Y_SCALE        147
#define IDS_GPAGE_STATIC_RANGE          148
#define IDD_DEBUG                       149
#define IDS_GENERAL_PAGE_RANGE_FROM     149
#define IDS_GPAGE_PROPS                 149
#define IDS_GPAGE_RANGE_TO              150
#define IDS_GPAGE_STATIC_HEIGHT         151
#define IDS_GPAGE_PROPS_PROPS           152
#define IDS_GPAGE_PROPS_STAMPS          153
#define IDS_GPAGE_RANGE_FROM_CHECK      154
#define IDS_GPAGE_RANGE_TO_CHECK        155
#define IDB_BITMAP48                    156
#define IDS_GPAGE_DATABLOCK_CHECK       156
#define IDD_SPLASH                      157
#define IDS_GPAGE_CHECK_HEIGHT          157
#define IDD_STAT_PAGE                   158
#define IDS_GPAGE_RANGE_FROM            158
#define IDD_PAGESETUP                   159
#define IDR_MULTIPLOTTYPE               159
#define IDS_MULTI_PROPS_DISTX           160
#define IDS_MULTI_PROPS_DISTY           161
#define IDS_MULTI_PROPS_TITLE           162
#define IDD_MEASURE                     163
#define IDS_MULTI_PROPS_PAGEBUTTON      163
#define IDD_BROWSE_PROFILES             164
#define IDS_MULTI_PROPS_DLGTITLE        164
#define IDS_MULTI_PROPS_DISTPANEL       165
#define IDR_ZRIGHT                      166
#define IDS_MULTI_PROPS_APPLY           166
#define IDR_ZLEFT                       167
#define IDS_MULTI_DOC_BAD_BOXES         167
#define IDS_OFFNEN_STATIC_PROJECT       168
#define IDS_OFFNEN_STATIC_WATER_STATE   169
#define IDS_OFFNEN_STATIC_PROFILES      170
#define IDS_OFFNEN_MULTIPLE_PLOT_CHECK  171
#define IDS_OFFNEN_CHECK_AUSRICHTUNG    172
#define IDS_OFFNEN_STATIC_AUSRICHTUNG   173
#define IDD_PROFILE_OV_XY               174
#define IDS_OEFFNEN_TITLE_DELETE        174
#define IDS_OEFFNEN_TITLE_OPEN          175
#define IDS_OEFFNEN_TITLE_INSERT        176
#define IDS_MARGINS_HOR                 177
#define IDS_MARGINS_VERT                178
#define IDS_MARGINS_RADIO_HOR           179
#define IDS_MARGINS_CHECK_HOR           179
#define IDS_MARGINS_RADIO_VERT          180
#define IDS_SHAREVIOLATION_STEMPEL      182
#define IDD_MULTI_PROPS                 186
#define IDR_ZEICHNEN                    202
#define IDR_MAINFRAME_NOHELP            218
#define IDC_PENCIL                      234
#define IDC_SIZEDIAG                    236
#define IDC_MAGNIFY                     237
#define IDD_ABOUTBOX                    1000
#define IDC_COMBO1                      1000
#define IDD_GENERAL                     1001
#define IDC_COMBO2                      1001
#define IDD_LINE                        1002
#define IDC_COMBO3                      1002
#define IDD_PREF                        1003
#define IDC_COMBO4                      1003
#define IDC_COMBO5                      1004
#define IDD_OPENPROJEKT                 1005
#define IDC_COMBO6                      1005
#define IDD_OFFNEN                      1006
#define IDC_COMBO7                      1006
#define IDD_TEXT                        1007
#define IDC_COMBO8                      1007
#define IDD_OPTION_OVERLAP              1008
#define IDC_COMBO9                      1008
#define IDD_STEMPEL                     1009
#define IDC_COMBO10                     1009
#define IDD_DATEN                       1010
#define IDC_COMBO11                     1010
#define IDD_PROP_LINE                   1011
#define IDC_COMBO12                     1011
#define IDD_ZOOM                        1012
#define IDC_COMBO13                     1012
#define IDD_PROP_SOLID                  1013
#define IDC_CHECK1                      1013
#define IDD_OPTION_SELTYPE              1014
#define IDC_CHECK2                      1014
#define IDD_PROP_TEXT                   1015
#define IDC_CHECK3                      1015
#define IDC_CHECK4                      1016
#define IDD_SOLID                       1017
#define IDC_BUTTON1                     1017
#define IDD_MARGINS                     1018
#define IDC_BUTTON2                     1018
#define IDD_FORMAT                      1019
#define IDC_BUTTON3                     1019
#define IDC_BUTTON4                     1020
#define IDC_EDIT1                       1021
#define IDC_EDIT2                       1022
#define IDC_EDIT3                       1023
#define IDC_EDIT4                       1024
#define IDC_EDIT5                       1025
#define IDC_EDIT6                       1026
#define IDC_EDIT7                       1027
#define IDC_EDIT8                       1028
#define IDC_EDIT9                       1029
#define IDC_EDIT10                      1030
#define IDC_EDIT11                      1031
#define IDC_SPIN1                       1032
#define IDC_SPIN2                       1033
#define IDC_STATIC1                     1034
#define IDC_STATIC2                     1035
#define IDC_STATIC3                     1036
#define IDC_STATIC4                     1037
#define IDC_STATIC5                     1038
#define IDC_STATIC6                     1039
#define IDC_STATIC7                     1040
#define IDC_STATIC8                     1041
#define IDC_STATIC9                     1042
#define IDC_TREE1                       1043
#define IDC_TREE2                       1044
#define IDC_LIST1                       1045
#define IDC_BIGICON                     1046
#define IDC_RADIO1                      1047
#define IDC_RADIO2                      1048
#define IDC_RADIO3                      1049
#define IDC_RADIO4                      1050
#define IDC_RADIO5                      1051
#define IDC_RADIO6                      1052
#define IDC_RADIO7                      1053
#define IDC_RADIO8                      1054
#define IDC_RADIO9                      1055
#define IDC_RADIO10                     1056
#define IDC_RADIO11                     1057
#define IDC_RADIO12                     1058
#define IDC_RADIO13                     1059
#define IDC_RADIO14                     1060
#define IDC_RADIO15                     1061
#define IDC_RADIO16                     1062
#define IDC_RADIO17                     1063
#define IDC_PROJEKT                     1064
#define IDC_SCROLLBAR1                  1065
#define IDC_PHYSICAL_MEM                1066
#define IDC_DISK_SPACE                  1067
#define IDC_TOOLBAR_ZOOMBOX             1068
#define IDC_TEMPLATE                    1069
#define IDC_STANDARD                    1070
#define IDC_BUTTON_LEFT                 1071
#define IDC_STATION_COMBO               1072
#define IDC_BUTTON_RIGHT                1073
#define IDC_BROWSE_COMBO                1074
#define IDC_EDIT_TEXT                   1075
#define IDC_STATIC_WIDTH                1077
#define IDC_STATIC_HEIGHT               1078
#define IDC_COMBO_WIDTH                 1079
#define IDC_COMBO_HEIGHT                1080
#define IDC_PHYSICAL_MEM_TEXT           1081
#define IDC_DISK_SPACE_TEXT             1082
#define IDC_DEMO_TEXT                   1083
#define IDC_LICENCE_TEXT                1084
#define IDC_MARGINS_MARGINS             1085
#define IDC_MARGINS_STATIC_TOP          1086
#define IDC_MARGINS_STATIC_LEFT         1087
#define IDC_MARGINS_STATIC_RIGHT        1088
#define IDC_MARGINS_STATIC_BOTTOM       1089
#define IDC_MARGINS_EDIT_TOP            1090
#define IDC_MARGINS_EDIT_LEFT           1091
#define IDC_MARGINS_EDIT_RIGHT          1092
#define IDC_MARGINS_EDIT_BOTTOM         1093
#define IDC_MARGINS_STATIC_HINT         1094
#define IDC_MARGINS_ALIGN               1095
#define IDC_MARGINS_STATIC_PROFIL       1096
#define IDC_MARGINS_STATIC_STEMPEL      1097
#define IDC_MARGINS_EDIT_DIST           1099
#define IDC_MARGINS_EDIT_VERT           1099
#define IDC_MARGINS_STATIC_DISC         1100
#define IDC_MARGINS_STAMP_STATIC        1100
#define IDC_MARGINS_COMBO_PROFIL        1101
#define IDC_PROP_TYPE_TEXT              1102
#define IDC_MARGINS_EDIT_HOR            1102
#define IDC_PROP_TYPE_ISPROFIL          1103
#define IDC_MARGINS_PROFIL_STATIC       1103
#define IDC_MARGINS_STATIC_STAMPSCALE   1104
#define IDC_MARGINS_EDIT_STAMPSCALE     1105
#define IDC_MARGINS_CHECK_STEMPEL       1106
#define IDC_GPAGE_STATIC_SCALE          1107
#define IDC_MARGINS_CHECK_HOR           1107
#define IDC_GPAGE_STATIC_X_SCALE        1108
#define IDC_GPAGE_STATIC_Y_SCALE        1109
#define IDC_GPAGE_X_COMBO               1111
#define IDC_GPAGE_Y_COMBO               1112
#define IDC_GPAGE_STATIC_RANGE          1113
#define IDC_GPAGE_RANGE_FROM            1115
#define IDC_GPAGE_RANGE_TO              1116
#define IDC_GPAGE_STATIC_HEIGHT         1117
#define IDC_GPAGE_CHECK_HEIGHT          1118
#define IDC_GPAGE_EDIT_HEIGHT           1119
#define IDC_GPAGE_HEIGHT_DEFAULT        1120
#define IDC_GPAGE_HINT                  1121
#define IDC_GPAGE_PROPS_PROPS           1122
#define IDC_GPAGE_PROPS_TEMPLATE_COMBO  1123
#define IDC_GPAGE_PROPS_STAMP           1124
#define IDC_GPAGE_PROPS_STAMP_COMBO     1125
#define IDC_GPAGE_PROPS                 1126
#define IDC_GPAGE_DATABLOCK_COMBO       1127
#define IDC_GPAGE_DATABLOCK_CHECK       1128
#define IDC_GPAGE_RANGE_FROM_CHECK      1129
#define IDC_GPAGE_RANGE_TO_CHECK        1130
#define IDC_GPAGE_RANGE_FROM_EDIT       1131
#define IDC_GPAGE_RANGE_TO_EDIT         1132
#define IDC_GPAGE_YSCALE                1134
#define IDC_OFFNEN_MULTIPLE_PLOT_CHECK  1135
#define IDC_MULTI_PROPS_TITLE_STATIC    1136
#define IDC_MULTI_PROPS_TITLE_EDIT      1137
#define IDC_MULTI_PROPS_DIST_STATIC     1138
#define IDC_MULTI_PROPS_DIST_X_STATIC   1139
#define IDC_MULTI_PROPS_DIST_X_EDIT     1140
#define IDC_MULTI_PROPS_DIST_Y_STATIC   1141
#define IDC_MULTI_PROPS_DIST_Y_EDIT     1142
#define IDC_MULTI_PROPS_PAGE_BUTTON     1143
#define IDC_MULTI_PROPS_APPLY           1144
#define IDC_OFFNEN_STATIC_AUSRICHTUNG   1145
#define IDC_OFFNEN_EDIT_AUSRICHTUNG     1146
#define IDC_OFFNEN_CHECK_AUSRICHTUNG    1147
#define IDC_OFFNEN_STATIC_PROJECT       1148
#define IDC_OFFNEN_STATIC_WATER_STATE   1149
#define IDC_OFFNEN_STATIC_PROFILES      1150
#define IDC_MARGINS_STATIC_VERT         1151
#define IDC_MARGINS_STATIC_HOR          1152
#define ID_CANCEL_EDIT_CNTR             8000
#define ID_VIEW_GRID                    8001
#define ID_OBJECT_MOVETOFRONT           8002
#define ID_OBJECT_MOVETOBACK            8003
#define ID_EDIT_ZOOM                    8004
#define ID_OBJECT_MOVEBACK              8005
#define ID_OBJECT_MOVEFORWARD           8006
#define ID_VIEW_SHOWOBJECTS             8007
#define ID_BUTTON_TEXT                  8009
#define ID_BUTTON_LINE                  8010
#define ID_BUTTON_RECHTECK              8011
#define ID_BUTTON_POINTER               8012
#define ID_DRAW_SELECT                  8013
#define ID_DRAW_LINE                    8014
#define ID_DRAW_RECT                    8015
#define ID_DRAW_TEXT                    8016
#define ID_DRAW_ELLIPSE                 8017
#define ID_DRAW_POLYLINE                8018
#define ID_FILE_PRINT_ALL               8019
#define ID_OBJECT_PROPERTIES            8020
#define ID_EXTRAS_OPTIONS               8021
#define ID_FILE_INSERT                  8022
#define ID_FILE_OPENPROJEKT             8023
#define ID_EDIT_PROPS                   8024
#define ID_EXTRAS_STEMPEL               8025
#define ID_EXTRAS_PREF                  8026
#define ID_FILE_CLOSEPROJEKT            8027
#define ID_CANCEL_EDIT_SRVR             8028
#define ID_FILE_DELETE                  8029
#define ID_OBJECT_DEBUG                 8031
#define ID_DRAW_POLYGON                 8032
#define ID_VIEW_ZOOMIN                  8036
#define ID_VIEW_ZOOMOUT                 8037
#define ID_FILE_SUMMARYINFO             8042
#define ID_WINDOW_CLOSEALL              8043
#define ID_FILE_DXF_EXPORT              8044
#define ID_EXTRAS_MEASURE               8045
#define ID_DRAW_MEASURE                 8046
#define ID_EDIT_BROWSE                  8047
#define ID_BROWSE_LEFT                  8048
#define ID_BROWSE_RIGHT                 8049
#define ID_FILE_OVERVIEW                8053
#define ID_PROFIL_OV_XY                 8055
#define ID_OBJECT_ISPROFIL              8056
#define ID_DUMMY                        8058
#define ID_MULTI_PROPS                  8060
#define IDB_PATTRN01                    32429
#define IDB_PATTRN02                    32430
#define IDB_PATTRN03                    32431
#define IDB_PATTRN04                    32432
#define IDB_PATTRN05                    32433
#define IDB_PATTRN06                    32434
#define IDB_PATTRN07                    32435
#define IDB_PATTRN08                    32436
#define IDB_PATTRN09                    32437
#define IDB_PATTRN10                    32438
#define IDB_PATTRN11                    32439
#define IDB_PATTRN12                    32440
#define IDB_PATTRN13                    32441
#define IDB_PATTRN14                    32442
#define IDB_PATTRN15                    32443
#define IDB_PATTRN16                    32444
#define IDB_PATTRN17                    32445
#define IDB_PATTRN18                    32446
#define IDB_PATTRN19                    32447
#define IDB_PATTRN20                    32448
#define IDB_PATTRN21                    32449
#define IDB_PATTRN22                    32450
#define IDB_PATTRN23                    32451
#define IDB_PATTRN24                    32452
#define ID_VIEW_ZEICHNEN_BAR            0xE804
#define IDW_ZEICHNEN_BAR                0xE804
#define ID_VIEW_PLOTBAR                 0xE805
#define IDW_PROFIL_OVERVIEW             0xE806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         8061
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
