//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WspDlg.rc
//
#define IDS_ERROR_START_GRTH_END        1
#define IDS_ERROR_READFILE              2
#define IDS_TOO_FEW_CSECTIONS           14
#define IDS_TOO_FEW_OUTFLOWS            15
#define IDS_WARNING_ABFLUSS             16
#define IDS_WARNING_ANFANG              17
#define IDS_WARNING_ENDE                18
#define IDS_NOTENOUGHPROFILS            21
#define IDS_DEMO_NOSAVE                 22
#define IDS_NONAME                      23
#define IDS_BUFFERTOOSMALL              40
#define IDS_TOOMANYPROFILS              41
#define IDS_QMINQMAX                    42
#define IDS_QSTEP                       43
#define IDS_ERROR_END_GRTH_START        45
#define IDS_VALUE1                      46
#define IDS_VALUE2                      47
#define IDS_NUM                         48
#define IDS_KRONENFORM                  49
#define IDS_UEBERFALLBEIWERT            50
#define IDS_COMMENT                     51
#define IDS_VALUE                       52
#define IDS_AX                          53
#define IDS_AY                          54
#define IDS_DP                          55
#define IDS_UNKNOWN                     59
#define IDS_CALCDATA                    60
#define IDS_QUEFILES_ALLFILES           61
#define IDS_OPTIONS                     62
#define IDS_VART1                       63
#define IDS_VWERT1                      64
#define IDS_VART2                       65
#define IDS_VWERT2                      66
#define IDS_VART3                       67
#define IDS_VWERT3                      68
#define IDS_VART4                       69
#define IDS_VWERT4                      70
#define IDS_VART5                       71
#define IDS_VWERT5                      72
#define IDS_INFLOW                      73
#define IDS_KRUEMMER                    74
#define IDS_EXTRAV                      75
#define IDS_CALCD                       76
#define IDS_OUTFLOW                     77
#define IDS_PROJOV                      88
#define IDD_LWACALC_PAGE1               102
#define IDD_STANDARD_PAGE               106
#define IDD_PROGRESS                    130
#define IDD_PROJECT_SUMM                132
#define IDD_LOSS                        148
#define IDD_PROJECT_PRINT               154
#define IDD_BEIWERT_DB                  155
#define IDD_KOPF_TXT                    156
#define IDD_LWACALC_PAGE2               317
#define IDD_LWACALC_PAGE3               318
#define IDD_LWACALC_PAGE4               319
#define IDD_BCECALC_PAGE1               320
#define IDD_BCECALC_PAGE2               321
#define IDD_BCECALC_PAGE3               323
#define IDD_RESOLUTION_PAGE             324
#define IDD_DIR_PAGE                    325
#define IDD_PROFILEDITOR_PAGE           326
#define IDC_EDIT1                       1007
#define IDC_COMBO1                      1008
#define IDC_EDIT2                       1008
#define IDC_COMBO2                      1009
#define IDC_EDIT3                       1009
#define IDC_CHECK1                      1010
#define IDC_COMBO4                      1010
#define IDC_CHECK2                      1011
#define IDC_COMBO5                      1011
#define IDC_EDIT10                      1011
#define IDC_RADIO1                      1012
#define IDC_CHECK3                      1012
#define IDC_RADIO2                      1013
#define IDC_CHECK4                      1013
#define IDC_RADIO3                      1014
#define IDC_RADIO4                      1015
#define IDC_EDIT8                       1015
#define IDC_CHECK6                      1015
#define IDC_RADIO5                      1016
#define IDC_CHECK7                      1016
#define IDC_EDIT9                       1017
#define IDC_CHECK8                      1017
#define IDC_RADIO13                     1017
#define IDC_RADIO6                      1018
#define IDC_CHECK9                      1018
#define IDC_RADIO7                      1019
#define IDC_CHECK10                     1019
#define IDC_RADIO8                      1020
#define IDC_COMBO6                      1021
#define IDC_CHECK13                     1021
#define IDC_RADIO9                      1022
#define IDC_EDIT15                      1022
#define IDC_EDIT4                       1023
#define IDC_EDIT16                      1023
#define IDC_EDIT5                       1024
#define IDC_RADIO10                     1025
#define IDC_RADIO11                     1026
#define IDC_RADIO12                     1027
#define IDC_CHECK11                     1028
#define IDC_PROGRESS1                   1028
#define IDC_CHECK12                     1029
#define IDC_STATIC1                     1029
#define IDC_TREE1                       1030
#define IDC_STATIC2                     1030
#define IDC_LIST1                       1031
#define IDC_STATIC3                     1031
#define IDC_LIST2                       1032
#define IDC_CHECK5                      1032
#define IDC_STATIC4                     1032
#define IDC_BUTTON1                     1062
#define IDC_BUTTON2                     1063
#define IDC_BUTTON3                     1064
#define IDC_BUTTON4                     1065
#define IDC_EDIT6                       1065
#define IDC_RADIO_VORWAERTS             1076
#define IDC_RADIO_RUECKWAERTS           1077
#define IDC_STATIC_SORT_HEAD            1078
#define IDC_STATIC_SORT_DIRECTION       1079
#define IDC_PE_PAGE_GROUP               1090

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
