//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.30 at 03:28:54 PM CEST 
//


package com.google.earth.kml;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.google.earth.kml.StyleMapPairType;
import com.google.earth.kml.StyleStateEnum;


/**
 * <p>Java class for StyleMapPairType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StyleMapPairType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="key" type="{http://earth.google.com/kml/2.1}styleStateEnum"/>
 *         &lt;element ref="{http://earth.google.com/kml/2.1}styleUrl"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "StyleMapPairType", propOrder = {

})
public class StyleMapPairType {

    @XmlElement(namespace = "http://earth.google.com/kml/2.1")
    protected StyleStateEnum key;
    @XmlElement(namespace = "http://earth.google.com/kml/2.1")
    protected String styleUrl;

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link StyleStateEnum }
     *     
     */
    public StyleStateEnum getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link StyleStateEnum }
     *     
     */
    public void setKey(StyleStateEnum value) {
        this.key = value;
    }

    /**
     * Gets the value of the styleUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyleUrl() {
        return styleUrl;
    }

    /**
     * Sets the value of the styleUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyleUrl(String value) {
        this.styleUrl = value;
    }

}
