//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.10 at 05:19:05 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kalypso.wb.tu-harburg.de/rrm/kalininmiljukov", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.tu_harburg.wb.kalypso.rrm.kalininmiljukov;
