DROP TABLE CROSS_SECTION CASCADE CONSTRAINTS;
DROP TABLE CROSS_SECTION_PART CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE INFO CASCADE CONSTRAINTS;
DROP TABLE POINT CASCADE CONSTRAINTS;
DROP TABLE POINT_KIND CASCADE CONSTRAINTS;
DROP TABLE ROUGHNESS CASCADE CONSTRAINTS;
DROP TABLE STATE CASCADE CONSTRAINTS;
DROP TABLE VEGETATION CASCADE CONSTRAINTS;
DROP TABLE WATERLEVEL_FIXATION CASCADE CONSTRAINTS;
DROP TABLE WATER_BODY CASCADE CONSTRAINTS;
DROP TABLE DOCUMENT CASCADE CONSTRAINTS;

DROP SEQUENCE  SEQ_PDB;

delete from USER_SDO_GEOM_METADATA where TABLE_NAME='DOCUMENT';
delete from USER_SDO_GEOM_METADATA where TABLE_NAME='CROSS_SECTION';
delete from USER_SDO_GEOM_METADATA where TABLE_NAME='CROSS_SECTION_PART';
delete from USER_SDO_GEOM_METADATA where TABLE_NAME='POINT';
delete from USER_SDO_GEOM_METADATA where TABLE_NAME='WATERLEVEL_FIXATION';
delete from USER_SDO_GEOM_METADATA where TABLE_NAME='WATER_BODY';
commit; 