<?xml version="1.0" encoding="UTF-8"?>
<NAModellControl fid="ID000000" xmlns="org.kalypso.namodell.control" xmlns:gml="http://www.opengis.net/gml" xmlns:obslink="obslink.zml.kalypso.org" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="org.kalypso.namodell.control project:/.model/schema/nacontrol.xsd">
  <description>Testberechnung</description>
  <name>Berechnung im Expertenmodus</name>
  <editor>Editor</editor>
  <comment>Kommentar</comment>
  <calctime>2001-12-17T09:30:47</calctime>
  <startsimulation>1998-09-01T01:00:00</startsimulation>
  <startforecast>1995-09-04T12:00:00</startforecast>
  <endsimulation>1995-09-09T01:00:00</endsimulation>
  <timeStep>0.083</timeStep>
  <tmp>true</tmp>
  <pre>true</pre>
  <sch>true</sch>
  <bof>true</bof>
  <bsp>true</bsp>
  <gws>true</gws>
  <qgs>true</qgs>
  <qgg>true</qgg>
  <qna>true</qna>
  <qif>true</qif>
  <qvs>true</qvs>
  <qbs>true</qbs>
  <qt1>true</qt1>
  <qtg>true</qtg>
  <qgw>true</qgw>
  <kap>true</kap>
  <vet>true</vet>
  <hyd>true</hyd>
  <bil>true</bil>
  <nmq>true</nmq>
  <spi>true</spi>
  <sub>true</sub>
  <sph>true</sph>
  <spv>true</spv>
  <spn>true</spn>
  <vep>true</vep>
  <automaticCallibration>false</automaticCallibration>
  <Catchments>//Catchment</Catchments>
  <CatchmentsBianf/>
  <CatchmentsFaktorRetobTetint/>
  <CatchmentsFaktn/>
  <CatchmentsFaktorAigw/>
  <KMChannels>//KMChannel</KMChannels>
  <KMChannelsFaktorRkf/>
  <KMChannelsFaktorRnf/>
  <rootNode/>
  <resultForRootNodeOnly>false</resultForRootNodeOnly>
  <pegelZR/>
  <qberechnetZR/>
</NAModellControl>
