//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WSPMap.rc
//
#define ID_BUTTON_LOG                   3
#define IDS_ERROR_READFILE              17
#define IDS_NONAME                      18
#define IDS_FILEINUSE                   19
#define IDS_NAMEUSED                    20
#define IDS_CANTFINDFILE                21
#define IDS_FIELDSTRINGS                22
#define IDS_SAMEFIELDS                  23
#define IDS_REMOVEDATASET               24
#define IDS_CANT_FIND_WSPWIN            25
#define IDS_HMOFILE1                    26
#define IDS_HMOFILE2                    27
#define IDS_SHAPEFILE                   28
#define IDS_ALL                         29
#define IDS_GEWAESSER                   30
#define IDS_ZUSTAND                     31
#define IDS_PROFIL_AUSWAHL_DELETE_TITLE 32
#define IDS_PROFIL_AUSWAHL_DELETE_TEXT  33
#define IDS_DELETE_PROFILE_FROM_MAP     34
#define IDS_NO_POINTS_FOUND             35
#define IDS_DIRECTORYUP                 36
#define IDS_ALLFORMATS                  37
#define IDS_RASTERDATA                  38
#define IDS_PRINT_Map_ALIGN_TEXT        39
#define IDS_BUFFERTOOSMALL              40
#define IDS_LOAD_PROFILES               41
#define IDS_HMOFILTER                   42
#define IDS_DELETE_SHAPES               43
#define IDS_LEGENDBAR_TITLE             44
#define IDS_WLEVEL                      45
#define IDS_WATER_LEVEL                 46
#define IDS_PROFILBAR_TITLE             47
#define IDS_HMO_IMPORT_FILTER           48
#define IDS_FORMAT_UNKNOWN              49
#define IDS_ERROR_READ_DTM              50
#define IDS_PROFILE_LINES               51
#define IDS_PROFILE_POINTS              52
#define IDS_SEP_AREA                    53
#define IDS_FLOW_AREA                   54
#define IDS_ERROR_ACCESS_TMP_DIR        55
#define IDS_THEME1                      56
#define IDS_PROFILES                    57
#define IDS_POINTS                      58
#define IDS_SEP                         59
#define IDS_FLOW                        60
#define IDS_ERROR_CREATE_TMP_DIR        61
#define IDS_NO_TRIANGLES                62
#define IDS_THEME2                      63
#define IDS_1OBJECTFOUND                64
#define IDS_NOBJECTSFOUND               65
#define IDS_NOACTIVETHEME               66
#define IDS_ACTIVETHEME                 67
#define IDS_WHOLENUM                    68
#define IDS_DECIMAL                     69
#define IDS_DATE                        70
#define IDS_TEXT                        71
#define IDS_BOOLEAN                     72
#define IDS_PRINT_MAP_ALIGN_NW          73
#define IDS_TYPE                        74
#define IDS_VALUEN                      75
#define IDS_SHAPEFILE_OR_ALLFILES       76
#define IDS_FIELDNAME                   77
#define IDS_FIELDTYPE                   78
#define IDS_VALUE                       79
#define IDS_POINT                       80
#define IDS_LINE                        81
#define IDS_POLYGON                     82
#define IDS_TRUE                        83
#define IDS_FALSE                       84
#define IDS_DELETE                      85
#define IDS_PRINT_MAP_ALIGN_NE          86
#define IDS_HMOFILES_OR_ALLFILES        87
#define IDS_THEME                       88
#define IDS_TRIANGULATON_ERROR          89
#define IDS_LOAD_LAYER_ERROR            90
#define IDS_WLINES                      91
#define IDS_MODELL_BOUNDS               92
#define IDS_WSPWIN_SAVING_PROJECT       93
#define IDS_TINFILES_OR_ALLFILES        94
#define IDS_VECTORDATA                  95
#define IDS_SMSFILES_OR_ALLFILES        96
#define IDS_BUHNEN                      97
#define IDS_MODELL_SHP                  98
#define IDS_BANK                        99
#define IDD_ABOUTBOX                    100
#define IDS_PROFILEDITOR_TITLE          100
#define IDS_BANK_SHP                    101
#define IDD_MAP_FORM                    102
#define ID_PROF_EDITOR_STATUS_STATION   102
#define IDS_NO_RESTRICTION              103
#define IDD_PREVIEW                     104
#define IDS_WRONG_EXPORT_FORMAT         104
#define IDS_BUHNE                       105
#define IDS_PROFILAUSWAHL_TITLE         106
#define IDS_CAD_DRAWINGS                107
#define IDD_LEGENDBAR                   108
#define IDS_ALL_VECTOR_FORMATS          108
#define IDS_FLOOD_BORDER                109
#define IDS_PHYSICAL_MEM                110
#define IDS_LINKSRECHTS                 111
#define IDS_DISK_SPACE                  112
#define IDS_ALL_IMAGE_FORMATS           113
#define IDS_ALL_FILES                   114
#define IDS_DISK_SPACE_UNAVAIL          115
#define IDR_MAPBAR                      116
#define IDS_SAVE_MAP_TEMPLATE           116
#define IDS_NUTKLASS_ZOTABLE            117
#define IDS_TOO_MANY_FILES_SELECTED     118
#define IDR_TOOLSBAR                    118
#define IDR_MAPPROJECTTYPE              119
#define IDR_PROFILAUSWAHL               119
#define IDS_PIVOT_POINTS                120
#define IDS_PIVOT_SHP                   121
#define IDS_USER_RW                     122
#define IDS_USER_RW_SHP                 123
#define IDS_USER_DEFINED                124
#define IDS_NO_VALID_OPERATION_PROFILES 125
#define IDS_COPY                        126
#define IDS_ERROR_WRITING_TMP_FILE      127
#define IDS_TINCUT_FAILED               128
#define IDS_PRINT_MAP_ALIGN_SW          129
#define IDS_SAVE_ALL_CHANGES_IN_MAP     130
#define IDS_DLG_AUTO_EXPORT_TITLE       131
#define IDS_MAIN_STREAM                 132
#define IDS_VORLAND                     133
#define IDS_RETENTION                   134
#define IDS_NUTZKLASS_BUTTON_NEW        135
#define IDD_MAP_OPEN                    136
#define IDS_NUTZKLASS_BUTTON_OK         136
#define IDD_INSERTDATA                  137
#define IDS_NUTZKLASS_VON               137
#define IDS_NUTZKLASS_TITLE             138
#define IDS_NUTZKLASS_ERROR_NAME        139
#define IDS_VERSCHNEID_TITLE            140
#define IDS_VERSCHNEID_NUTZ             141
#define IDS_VERSCHNEID_PROFIL           142
#define IDS_VERSCHNEID_FIELDS_NUTZ      143
#define IDS_VERSCHNEID_ART_PROFIL       144
#define IDR_OVERVIEW_POPUP              145
#define IDS_VERSCHNEID_ART_NUTZ         145
#define IDR_LEGEND_POPUP                146
#define IDS_VERSCHNEID_FIELDS_PROFIL    146
#define IDR_SCALEBAR_POPUP              147
#define IDS_VERSCHNEID_STATIC_UFER      147
#define IDS_VERSCHNEID_LEFT             148
#define IDS_VERSCHNEID_RIGHT            149
#define IDS_VERSCHNEID_PROGRESS         150
#define IDS_DATABLOCKS_HEADING          151
#define IDS_DATABLOCKS_TITLE            152
#define IDB_BIGTEXT                     153
#define IDS_NUTZKLASS_ERROR_DOUBLE_NAME 153
#define IDD_NEW_MAP                     154
#define IDS_EXTENDPROFILE_TITEL         154
#define IDB_BITMAP48                    155
#define IDS_EXTENDPROFILE_OKTEXT        155
#define IDD_OBJECT_QUERY                156
#define IDS_CUT_LINE_WITH_DGM           156
#define IDD_SAVE_PROFILE_CHANGES        157
#define IDS_ADD_POINTS_TO_MAP           157
#define IDS_UPDATE_DATA                 158
#define IDS_PROFILE_EXTEND_NO_POINTS    159
#define IDS_TRACK_RIVER                 160
#define IDS_TRACK_PROFILE               161
#define IDS_ERROR_RIVER_CUTS_PROFILE    162
#define IDS_GENERATEPROFILE_TITEL       163
#define IDD_NEW_LAYER                   164
#define IDS_GENERATEPROFILE_OKTEXT      164
#define IDS_ERROR_RIVER_CUTS            165
#define IDS_SAVE_PROFILES               166
#define IDS_PROFILE_SAVE_SUCCES         167
#define IDS_WRITE_MAP_TO_PROFILES       168
#define IDS_PROFILE_FILE                169
#define IDS_PRED_PROFILE                170
#define IDS_FOLLOW_PROFILE              171
#define IDS_NEW_PROFILE                 172
#define IDS_RIVER                       173
#define IDS_STRANG_DISTANCE             174
#define IDS_PRINT_MAP_ALIGN_SE          175
#define IDS_LEFT                        176
#define IDS_RIGHT                       177
#define IDD_IMAGE_PROPS                 178
#define IDS_PROFGEN_ERROR_NICHT_BENACHBART 178
#define IDD_FILE_PRINT_SCALE            179
#define IDS_PROFGEN_ERROR_VERSCH_ZUSTAENDE 179
#define IDS_PROFGEN_ERROR_PROJECT       180
#define IDS_PROFGEN_ERROR_NOTLAST       181
#define IDS_PROFGEN_NO_EMPTYSTATES      182
#define IDS_GENPROFILE_DESCRIPTION      183
#define IDS_GENPROFILE_DIGITRIVER       184
#define IDS_GEN_PROFILE_WSPWIN_OPEN     185
#define IDS_TINCUT_OBS_DLG_TITLE        186
#define IDS_TINCUT_USER_BREAK           187
#define IDS_ERROR_HMO_TRIANG            188
#define IDS_ERROR_CREATE_LAYER          189
#define IDS_CUT_LINES_ADDING_POINTS     190
#define IDS_CUT_LINES_CUTTING           191
#define IDS_CUT_THEME_NO_LINES          192
#define IDD_SHAPE_TO_PROFILE            193
#define IDS_CUT_THEME_UPDATE_POINTS     193
#define IDD_PROGRESSDLG                 194
#define IDS_VERSCHNEID_DELETE_THEME     194
#define IDS_MOVE_OBJECT_OUT             195
#define IDS_COUNT_TOO_BIG               196
#define IDD_TINCUT                      197
#define IDD_DGM                         197
#define IDS_NUTZKLASS_BUTTON_DELCOL     197
#define IDS_DATA_ERROR_MSG              198
#define IDS_ERROR_CUT_COUNT_COORDS      199
#define IDS_CUT_LINES_ADDING_PROFILE_POINTS 200
#define IDS_CUT_LINES_READING_DATA      201
#define IDS_CUT_LINES_DELETE_POINTS     202
#define IDS_NUTZKLASS_ERROR_INPUT       203
#define IDS_NUTZKLASS_ADD_COL           204
#define IDS_NUTZKLASS_DEL_COL           205
#define IDS_NUTZKLASS_DEL_ROW           206
#define IDS_PREVIEW_CLOSE               207
#define IDS_PREVIEW_NUMPAGE             208
#define IDS_PREVIEW_NEXT                209
#define IDS_PREVIEW_PREV                210
#define IDS_PREVIEW_PRINT               211
#define IDD_PROFILEDITOR                212
#define IDS_PREVIEW_ZOOMIN              212
#define IDS_PREVIEW_ZOOMOUT             213
#define IDD_SHAPE_TO_PROFILE_RESTRICTION 214
#define IDS_PRINTER_SETUP               214
#define IDS_PREVIEW_PRINTER_SETUP       215
#define IDS_PREVIEW_SELECT              216
#define IDS_PREVIEW_NEW_TEXT            217
#define IDS_PRINT_PROP_PAGE             218
#define IDS_PRINT_BORDER_PAGE           219
#define IDD_PROFIL_AUSWAHL              220
#define IDS_PRINT_PROP_CAPTION          220
#define ID_PROFILE_LIST                 221
#define ID_PROFILAUSWAHL_TREE_CTRL      222
#define ID_INFORMBAR                    223
#define ID_INFORM_BUHNE                 223
#define ID_INFORM                       224
#define ID_INFORM_LAENGSW               224
#define IDD_AUTO_EXPORT                 225
#define ID_INFORM_SOHLHOCH              225
#define ID_INFORM_SOHLTIEF              226
#define ID_INFORM_VORLHOCH              227
#define ID_INFORM_VORLTIEF              228
#define ID_INFORM_UFERAUS               229
#define ID_INFORM_UFERABG               230
#define ID_INFORM_DEICH                 231
#define IDS_PREVIEW_NEW_LEGEND          232
#define IDR_HELP                        233
#define IDS_PREVIEW_NEW_MAP             233
#define IDR_WINDOW                      234
#define IDS_PREVIEW_DELETE              234
#define IDR_TOOLS                       235
#define IDS_PREVIEW_PROPS               235
#define IDS_PREVIEW_ZFRONT              236
#define IDR_THEME                       237
#define IDR_THEMEBAR                    237
#define IDS_PREVIEW_ZBACK               237
#define IDR_MAP                         238
#define IDS_PREVIEW_NEW_LOGO            238
#define IDR_VIEW                        239
#define IDS_TEST_LAYER_TYPE_FAILED      239
#define IDR_OBJECT                      240
#define IDS_PRINT_MAP_SCALE             240
#define IDS_PRINT_MAP_RADION_EXTENT     241
#define IDS_PRINT_MAP_RADION_PRINTRECT  242
#define IDR_OBJECTBAR                   243
#define IDS_PRINT_MAP_ALIGN_NONE        243
#define IDS_LAYER_COPY_FAILED           244
#define IDR_MAINMAP                     245
#define IDS_COPY_LAYER_UNIQUE_AXIS      245
#define IDR_MAINVIEW                    246
#define IDS_GENERATE_PROFILES_NO_STATION_ATTRIBUTE 246
#define IDR_HELPBAR                     247
#define IDS_ERROR_RIVER_CUTS_PROFILE_MULTIPLE 247
#define IDR_MAINFRAME                   248
#define IDR_MAPTYPE                     249
#define IDR_FILEBAR                     250
#define IDS_ERROR_RIVER_CUTS_MULTIPLE_TITLE 250
#define IDS_GENERATE_PROFILES_SUCCESS   251
#define IDS_COPY_LAYER_CHOOSER_TITLE    252
#define IDS_COPY_LAYER_CHOOSER_TEXT     253
#define IDS_RIVER_AXIS                  254
#define IDS_DEMO_TEXT1                  255
#define IDS_CUT_LINES_WSP_QUEST_TITLE   256
#define IDS_CUT_LINES_WSP_QUEST_TEXT    257
#define IDS_PREVIEW_NEW_LEGEND2         258
#define IDS_FEHLER_PROFILE_LADEN_RWHW   259
#define IDS_AUSUENN_TEXT                260
#define IDS_AUSUENN_MSG                 261
#define IDS_EXTEND_PROFILE_TITLE        262
#define IDS_GENPROFILE_TITLE            263
#define IDS_PROFILE_OVERVIEW_REMOVE_PRF 264
#define IDR_INFORMBAR                   265
#define IDS_PROFILE_OVERVIEW_SAVE_PRF   265
#define IDS_PROFIL_AUSWAHL_MISSING_PRFS 266
#define IDS_MAP_LAYER_PROPS_TITLE       267
#define IDD_NUTZKLASS                   268
#define IDS_IMAGE_PROPS_COLOR           268
#define IDR_EXTRAS                      269
#define IDS_IMAGE_PROPS_FILE            269
#define IDD_VERSCHNEID                  270
#define IDS_IMAGE_PROPS_NAME            270
#define IDD_UPDATA_DATABLOCKS           271
#define IDS_IMAGE_PROPS_TRANSPARENT     271
#define IDD_GENERATE_PROFILE            272
#define IDS_IMAGE_PROPS_TITLE           272
#define IDD_OBSERVER                    273
#define IDS_LAYER_FILEFILTER            273
#define IDD_PREVIEW_BAR                 279
#define IDD_DIALOG1                     296
#define IDD_VOLUME_DIALOG               299
#define IDD_STRANG_DISTANCES            301
#define IDS_SAVEPRCHANGES_AREAS         500
#define IDS_SAVEPRCHANGES_THEMES        501
#define IDS_SAVEPRCHANGES_KINDOFAREA    502
#define IDS_SAVEPRCHANGES_FIELDS        503
#define IDS_SAVEPRCHANGES_PRODATA       504
#define IDS_SAVEPRCHANGES_MODELL        505
#define IDS_SAVEPRCHANGES_DURCHST       506
#define IDS_SAVEPRCHANGES_BOESCHUNG     507
#define IDS_SAVEPRCHANGES_TRENN         508
#define IDS_SAVEPRCHANGES_BUHNEN        509
#define IDS_SAVEPRCHANGES_STATION       510
#define IDS_SAVEPRCHANGES_CANCEL        511
#define IDS_SAVEPRCHANGES_OK            512
#define IDS_SAVEPRCHANGES_TITLE         513
#define IDD_OPENPROJEKT                 1000
#define IDD_SCALEBAR                    1001
#define IDD_OVERVIEWBAR                 1002
#define IDD_SPLASH                      1003
#define IDC_ALIGN_MIDLEFT               1004
#define IDC_ALIGN_BOTTOMLEFT            1005
#define IDC_ALIGN_TOPCENTER             1006
#define IDC_ALIGN_MIDCENTER             1007
#define IDC_ALIGN_BOTTOMCENTER          1008
#define IDC_ALIGN_MIDRIGHT              1009
#define IDD_VALUE_SYMBOL_PAGE           1010
#define IDC_SBSCALEBAR1                 1012
#define IDD_SINGLE_SYMBOL_PAGE          1013
#define IDC_OVERVIEWMAP                 1014
#define IDD_BREAKS_SYMBOL_PAGE          1015
#define IDC_OVERVIEWLIST                1016
#define IDD_STNDRD_LABEL_PAGE           1017
#define IDC_LEGENDLIST                  1018
#define IDD_ADVNCD_LABEL_PAGE           1019
#define IDD_VIEW_PROFILE                1020
#define IDD_OPEN_LAYER                  1021
#define IDD_PRINT_BORDER_PAGE           1021
#define IDC_PHYSICAL_MEM                1022
#define IDD_PRINT_TEXT_PAGE             1022
#define IDD_PRINT_MAP_PAGE              1023
#define IDC_DISK_SPACE                  1024
#define IDD_PRINT_OLE_PAGE              1024
#define IDD_PRINT_IMAGE_PAGE            1025
#define IDC_BUTTON1                     1026
#define IDD_PRINT_LEGEND_PAGE           1026
#define IDC_BUTTON2                     1027
#define IDD_PRINT_LEGEND2_PAGE          1027
#define IDC_EDIT1                       1028
#define IDC_EDIT2                       1030
#define IDC_SPIN1                       1033
#define IDC_MAP1                        1036
#define IDC_COMBO1                      1038
#define IDC_COMBO2                      1039
#define IDC_COMBO3                      1040
#define IDC_COMBO4                      1041
#define IDC_COMBO5                      1042
#define IDC_CHECK1                      1043
#define IDC_CHECK2                      1044
#define IDC_CHECK3                      1045
#define IDC_CHECK4                      1046
#define IDC_COMBO6                      1048
#define IDC_BIGICON                     1053
#define IDC_SLIDER1                     1054
#define IDC_SLIDER2                     1055
#define IDC_SLIDER3                     1056
#define IDC_RADIO1                      1058
#define IDC_RADIO2                      1059
#define IDC_RADIO3                      1060
#define IDC_RADIO4                      1061
#define IDC_RADIO5                      1062
#define IDC_LIST1                       1063
#define IDC_RADIO6                      1064
#define IDC_STATIC1                     1065
#define IDC_RADIO7                      1066
#define IDC_STATIC2                     1067
#define IDC_RADIO8                      1069
#define IDC_FILELIST                    1070
#define IDC_STATIC3                     1071
#define IDC_STATIC4                     1073
#define IDC_IMPORT_TYPES                1074
#define IDC_LEGEND1                     1090
#define IDC_SPLASH_COPYRIGHT            1092
#define IDC_ABOUT_COPYRIGHT             1094
#define IDC_DRIVE                       1095
#define IDC_LAYERCOMBO                  1096
#define IDC_UFERRADIO_L                 1097
#define IDC_UFERRADIO_R                 1098
#define IDC_CHECK_TRENN                 1099
#define IDC_CHECK_DURCHST               1100
#define IDC_CHECK_BUHNEN                1101
#define IDC_CHECK_STATION               1102
#define IDC_THEMENLISTE                 1103
#define IDC_CHECK_BOESCHUNG             1104
#define IDC_COMBO_ART                   1105
#define IDC_COMBO_WERTFELD              1106
#define IDC_TEXTFELD                    1107
#define IDC_PROGRESS                    1108
#define IDC_HMO_COMBO                   1115
#define IDC_HMO_PATH                    1116
#define IDC_CHECK_MODELL                1122
#define IDC_LEGENDE                     1123
#define IDC_DRAW_AREA                   1132
#define IDC_YAXIS                       1133
#define IDC_ZAXIS                       1134
#define IDC_FIELD_COMBO                 1137
#define IDC_FIELD_VALUE                 1138
#define IDC_SMALL                       1139
#define IDC_STATIC_AREAS                1140
#define IDC_STATIC_THEMES               1141
#define IDC_STATIC_KIND_OF_AREA         1142
#define IDC_STATIC_FIELDS               1143
#define IDC_STATIC_PROFILEDATA          1144
#define IDC_EXPORT_LIST                 1145
#define IDC_NUTZKLASS_STATIC_ZOTABLE    1146
#define IDC_NUTZKLASS_LISTCTRL          1147
#define IDC_NUTZKLASS_NAME_COMBO        1148
#define IDC_NUTZKLASS_NEW_BUTTON        1149
#define IDC_NUTZKLASS_EDIT              1150
#define IDC_NUTZKLASS_BUTTON_OK         1151
#define IDC_NUTZKLASS_BUTTON_CANCEL     1152
#define IDC_VERSCHNEID_RADIO_NUTZ       1153
#define IDC_VERSCHNEID_RADIO_PROFIL     1154
#define IDC_VERSCHNEID_COMBO_FIELDS     1155
#define IDC_VERSCHNEID_COMBO_TYPE       1156
#define IDC_VERSCHNEID_STATIC_ART       1157
#define IDC_VERSCHNEID_EDIT_CONSTRAINT  1159
#define IDC_FIELD_CHECK                 1160
#define IDC_VERSCHNEID_RADIO_LEFT       1161
#define IDC_VERSCHNEID_RADIO_RIGHT      1162
#define IDC_VERSCHNEID_STATIC_RELI      1163
#define IDC_DATABLOCKS_LIST             1165
#define IDC_DATABLOCKS_STATIC           1166
#define IDC_PROFILE_DUMMY               1167
#define IDC_DESCRIPTION                 1170
#define IDC_STATE_TEXT                  1171
#define IDC_PRED_TEXT                   1172
#define IDC_FOLLOWER_TEXT               1173
#define IDC_NEW_TEXT                    1174
#define IDC_FILE_TEXT                   1176
#define IDC_EDIT_FILE_PRED              1177
#define IDC_EDIT_FILE_FOLLOW            1178
#define IDC_EDIT_FILE_NEW               1179
#define IDC_STATION_TEXT                1180
#define IDC_EDIT_STATION_PRED           1181
#define IDC_EDIT_STATION_FOLLOW         1182
#define IDC_EDIT_STATION_NEW            1183
#define IDC_VZK_TEXT                    1184
#define IDC_EDIT_VZK_PRED               1185
#define IDC_EDIT_VZK_FOLLOW             1186
#define IDC_VOR_L_TEXT                  1187
#define IDC_EDIT_VOR_L_PRED             1188
#define IDC_EDIT_VOR_L_FOLLOW           1189
#define IDC_PK_TEXT                     1190
#define IDC_EDIT_PK_PRED                1191
#define IDC_EDIT_PK_FOLLOW              1192
#define IDC_COMBO_VZK                   1193
#define IDC_EDIT_PK_NEW                 1194
#define IDC_VOR_L_TEXT2                 1195
#define IDC_FLUSS_TEXT                  1195
#define IDC_EDIT_VOR_L_PRED2            1196
#define IDC_EDIT_FLUSS_PRED             1196
#define IDC_EDIT_VOR_L_FOLLOW2          1197
#define IDC_EDIT_FLUSS_FOLLOW           1197
#define IDC_VOR_L_TEXT3                 1198
#define IDC_VOR_R_TEXT                  1198
#define IDC_EDIT_VOR_L_PRED3            1199
#define IDC_EDIT_VOR_R_PRED             1199
#define IDC_EDIT_VOR_L_FOLLOW3          1200
#define IDC_EDIT_VOR_R_FOLLOW           1200
#define IDC_STRAND_DIST_TEXT            1201
#define IDC_STRANG_DIST_TEXT            1201
#define IDC_OBSERVER_PROGRESS           1202
#define IDC_OBSERVER_TEXT               1203
#define IDC_CHECK_DELETE_THEME          1204
#define IDC_NUTZKLASS_GRID              1206
#define IDC_NUTZKLASS_DELETE_COL        1207
#define IDC_NUTZKLASS_DELETE_ROW        1208
#define IDC_NUTZKLASS_ADD_COL           1209
#define IDC_NUTZKLASS_COL_COMBO         1210
#define IDC_PREVIEW_Y_TEXT              1212
#define IDC_PREVIEW_X_TEXT              1213
#define ID_PREVIEW_PRINTER_SETUP        1217
#define ID_PREVIEW_NEW_TEXT             1220
#define ID_PREVIEW_SELECT               1221
#define ID_PREVIEW_NEW_MAP              1223
#define ID_PREVIEW_NEW_LOGO             1224
#define ID_PREVIEW_NEW_LEGEND2          1225
#define IDC_RADIO_RIGHT                 1226
#define IDC_EDIT                        1227
#define IDC_PRINT_TEXT_EDIT             1227
#define IDC_PRINT_MAP_SCALETEXT         1229
#define IDC_PRINT_MAP_SCALECOMBO        1230
#define IDC_PRINT_MAP_RADIO_EXTENT      1231
#define IDC_PRINT_MAP_RADIO_PRINTRECT   1232
#define IDC_PRINT_OLE_BUTTON            1233
#define IDC_PRINT_TEXT_SCHRIFT          1234
#define IDC_PRINT_BORDER_COLOR          1238
#define IDC_PRINT_BORDER_WIDTH          1239
#define IDC_PRINT_BORDER_SPIN           1240
#define IDC_PRINT_BORDER_STYLE          1241
#define IDC_PRINT_BORDER_STYLE_STATIC   1242
#define IDC_PRINT_BORDER_WIDTH_STATIC   1243
#define IDC_PRINT_BORDER_COLOR_STATIC   1244
#define IDC_PRINT_IMAGE_TEXT            1245
#define IDC_PRINT_IMAGE_SEARCH          1246
#define IDC_PRINT_IMAGE_NAME            1247
#define IDC_PRINT_MAP_TEXT              1248
#define IDC_PRINT_MAP_ALIGN_COMBO       1249
#define IDC_PRINT_MAP_FONT_BUTTON       1250
#define IDC_STATIC_TEXT                 1251
#define IDC_STATIC_ALLIGN               1252
#define IDC_RADIO_CENTER                1253
#define IDC_RADIO_LEFT                  1254
#define IDC_PRINT_IMAGE_SIZE_CHECK      1255
#define IDC_PRINT_LEGEND_FIXSIZE        1256
#define IDC_PRINT_LEGEND2_PAGE_SCHRIFT  1257
#define IDC_BUTTON_AUSDUENN             1258
#define IDC_STATIC_COUNT                1259
#define IDC_EDIT_AUSDUENN               1260
#define IDC_STATIC_AUSDUENN             1261
#define IDC_IMAGE_PROPS_STATIC_FILE     1262
#define IDC_IMAGE_PROPS_EDIT_FILE       1263
#define IDC_IMAGE_PROPS_STATIC_NAME     1264
#define IDC_IMAGE_PROPS_CHECK_TRANSPARENT 1265
#define IDC_IMAGE_PROPS_STATIC_COLOR    1266
#define IDC_IMAGE_PROPS_BUTTON          1267
#define IDC_IMAGE_PROPS_EDIT            1268
#define IDC_SINGLE_SYMBOL_CHECK         1269
#define IDC_VOLUME_EDIT                 1270
#define IDC_LABEL                       1271
#define IDC_GRID                        1273
#define ID_INDICATOR_XCOORD             8030
#define ID_INDICATOR_YCOORD             8031
#define ID_INDICATOR_LAYER              8032
#define IDB_PATTRN01                    32429
#define IDB_PATTRN02                    32430
#define IDB_PATTRN03                    32431
#define IDB_LINE_SYMBOL                 32435
#define IDB_CIRCLE_SYMBOL               32436
#define IDB_SQUARE_SYMBOL               32437
#define IDB_TRIANGLE_SYMBOL             32438
#define IDB_CROSS_SYMBOL                32439
#define IDB_SOLID_FILL                  32440
#define IDB_TRANSPARENT_FILL            32441
#define IDB_HORIZ_FILL                  32442
#define IDB_VERT_FILL                   32443
#define IDB_UPDIAG_FILL                 32444
#define IDB_DNDIAG_FILL                 32445
#define IDB_CROSS_FILL                  32446
#define IDB_DIAGCROSS_FILL              32447
#define IDB_LTGRAY_FILL                 32448
#define IDB_GRAY_FILL                   32449
#define IDB_DKGRAY_FILL                 32450
#define IDB_SMALLTEXT                   32451
#define IDB_INVALIDLAYER                32452
#define ID_FILE_OPEN_PROJECT            32777
#define ID_FILE_CLOSE_PROJECT           32778
#define ID_MAP_NEW                      32787
#define ID_MAP_OPEN                     32788
#define ID_LAYER_INSERT                 32800
#define ID_LAYER_REMOVE                 32801
#define ID_LAYER_ZOOM                   32802
#define ID_LAYER_PROPERTIES             32803
#define ID_TOOLS_ZOOMIN                 32805
#define ID_TOOLS_ZOOMOUT                32806
#define ID_TOOLS_PAN                    32807
#define ID_FILE_SAVE_PROJECT            32810
#define ID_MAP_DELETE                   32812
#define ID_TOOLS_FULL_EXTENT            32813
#define ID_FILE_SAVEAS                  32817
#define ID_LAYER_MOVETOTOP              32824
#define ID_LAYER_MOVEFORWARD            32825
#define ID_LAYER_MOVEBACK               32826
#define ID_LAYER_MOVETOBACK             32827
#define ID_TOOLS_NONE                   32828
#define ID_LAYER_NEW                    32835
#define ID_OBJECT_NEW                   32847
#define ID_OBJECT_QUERY                 32848
#define ID_OBJECT_DELETE                32849
#define ID_TOOLS_EDIT_PROFIL            32851
#define ID_VIEW_MAPUNITS_DEGREES        32855
#define ID_VIEW_MAPUNITS_FEET           32856
#define ID_VIEW_MAPUNITS_METERS         32857
#define ID_VIEW_SCALEUNITS_MILES        32858
#define ID_VIEW_SCALEUNITS_FEET         32859
#define ID_VIEW_SCALEUNITS_METERS       32860
#define ID_VIEW_SCALEUNITS_KM           32861
#define ID_VIEW_SCREENUNITS_CM          32862
#define ID_VIEW_SCREENUNITS_INCHES      32863
#define ID_VIEW_OVERVIEW                32864
#define ID_VIEW_CLEAROVERVIEW_LEGENDE   32865
#define ID_OVERVIEW_LAYER               32866
#define ID_LAYER_OVERVIEW               32867
#define ID_FILE_MANAGER                 32870
#define ID_OBJECT_CHANGE                32875
#define ID_POINT_INSERT                 32876
#define ID_POINT_DELETE                 32877
#define ID_POINT_MOVE                   32878
#define ID_OBJECT_MOVE                  32880
#define ID_LAYER_SHAPE_TO_PROFILE       32881
#define ID_TESTBUTTON                   32882
#define ID_LAYER_TINCUT                 32883
#define ID_VIEW_PROFILEBAR              32886
#define ID_LAYER_HMO_IMPORT             32887
#define ID_TOOLS_FOLLOW_PROFILE         32888
#define ID_MAP_EXPORT_BMP               32889
#define ID_MAP_EXPORT_CLIBBOARD         32890
#define ID_MAP_SAVE_AS                  32891
#define ID_MAP_CLIPBOARD                32892
#define ID_OBJECT_CLIP                  32893
#define ID_PROFIL_AUSWAHL_REMOVE        32895
#define ID_PROFIL_AUSWAHL_ADD           32896
#define ID_PROFILAUSWAHL_SAVE           32897
#define ID_LAYER_COPY                   32898
#define ID_PROFILAUSWAHL_SELECTALL      32900
#define ID_SAFE_DEFAULT_PROPERTIES      32901
#define ID_TOOLS_MARK_PROFILE           32902
#define ID_LAYER_MOVE_OUTWARDS          32941
#define ID_EXTRAS_EDIT_NUTZUNG          32942
#define ID_TOOLS_GENERATE_PROFILE       32944
#define ID_TOOLS_EXTEND_PROFILE         32945
#define ID_ESCAPE                       32948
#define ID_PREVIEW_NEW_MAP_TOOL         32949
#define ID_LAYER_GENERATE_PROFILES      32950
#define ID_TOOLS_SHOW_CURSOR            32951
#define ID_LAYER_PROPERTIES_EXPORT      32952
#define ID_LAYER_PROPERTIES_IMPORT      32953
#define ID_EXTRAS_PROFILEDISTANCE       32954
#define ID_TOOLS_FLIP_PROFILE           32955
#define ID_PREVIEW_DELETE               58113
#define ID_PREVIEW_PROPS                58114
#define ID_PREVIEW_ZFRONT               58115
#define ID_PREVIEW_ZBACK                58119
#define ID_VIEW_OVERVIEW_MAP            0xE804
#define IDW_OVERVIEW_BAR                0xE804
#define ID_VIEW_MAPBAR                  0xE805
#define IDW_MAPBAR                      0xE805
#define ID_VIEW_LEGEND                  0xE806
#define ID_VIEW_SCALEBAR                0xE807
#define IDW_SCALE_BAR                   0xE807
#define ID_VIEW_PROFILAUSWAHL           0xE808
#define IDW_PROFIL_AUSWAHL              0xE808
#define IDW_PROFILAUSWAHL_TOOLBAR       0xE809
#define IDW_PROFIL_EDITOR               0xE80A

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        305
#define _APS_NEXT_COMMAND_VALUE         32956
#define _APS_NEXT_CONTROL_VALUE         1274
#define _APS_NEXT_SYMED_VALUE           225
#endif
#endif
