//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Interp.rc
//
#define IDS_INTERP                      1
#define IDS_PROFIL_DATA                 2
#define IDS_SELECT2ITEMS                3
#define IDS_NUMUSED                     4
#define IDS_BACKSPRING                  5
#define IDS_ERROR_NOGELAENDE            6
#define IDS_ERROR_INDEX                 7
#define IDS_VERTICAL                    8
#define IDS_KEYEXISTS                   9
#define IDS_PKEMPTY                     10
#define IDS_TOOMANYPOINTS               11
#define IDS_DEMO                        12
#define IDS_NOFILENAME                  13
#define IDS_NOFILEEXIST                 14
#define IDS_ERROR_READFILE              15
#define IDS_NOINTERP                    16
#define IDS_NOTBETWEEN                  17
#define IDS_INTERPOLATING               18
#define IDS_INTERP_OK                   19
#define IDS_INTERP_BAD                  20
#define IDS_SHIFTING                    21
#define IDS_SHIFT_OK                    22
#define IDS_SHIFT_BAD                   23
#define IDS_SOHLHOEHE                   25
#define IDS_LBVHOEHE                    26
#define IDS_RBVHOEHE                    27
#define IDS_NOBORDVOLL                  28
#define IDS_BV1_NOTINLEFT               29
#define IDS_BV2_NOTINRIGHT              30
#define IDS_URDATEI                     33
#define IDS_STATION_BOUNDS              34
#define IDS_ALLFILES                    35
#define IDS_ERROR_SAVEFILE              36
#define IDD_INTERP_DIALOG               102
#define IDD_INTERP_PAGE1                106
#define IDD_INTERP_PAGE2                107
#define IDD_INTERP_PAGE3                108
#define IDD_INTERP_PAGE4                109
#define IDR_MAINFRAME                   128
#define IDC_LIST1                       1000
#define IDC_EDIT1                       1002
#define IDC_EDIT2                       1003
#define IDC_EDIT4                       1005
#define IDC_EDIT5                       1006
#define IDC_EDIT6                       1008
#define IDC_STATIC2                     1010
#define IDC_EDIT3                       1011
#define IDC_STATIC1                     1012
#define IDC_STATIC3                     1013
#define IDC_BUTTON1                     1014
#define IDC_RADIO1                      1015
#define IDC_RADIO2                      1016
#define IDC_CHECK1                      1017
#define ID_INTERP_INTERP                32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
