-- Version setzen auf "creating" oder "updateing"
UPDATE INFO set value='updateing 0.0.2 to 0.0.3'  where key ='Version';

GRANT SELECT ON CROSS_SECTION TO PDB_USER;
GRANT SELECT ON CROSS_SECTION_PART TO PDB_USER;
GRANT SELECT ON EVENT TO PDB_USER;
GRANT SELECT ON INFO TO PDB_USER;
GRANT SELECT ON POINT TO PDB_USER;
GRANT SELECT ON POINT_KIND TO PDB_USER;
GRANT SELECT ON ROUGHNESS TO PDB_USER;
GRANT SELECT ON STATE TO PDB_USER;
GRANT SELECT ON VEGETATION TO PDB_USER;
GRANT SELECT ON WATERLEVEL_FIXATION TO PDB_USER;
GRANT SELECT ON WATER_BODY TO PDB_USER;
GRANT SELECT ON DOCUMENT TO PDB_USER;


GRANT DELETE, INSERT, SELECT, UPDATE ON CROSS_SECTION TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON CROSS_SECTION_PART TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVENT TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON INFO TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON POINT TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON POINT_KIND TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON ROUGHNESS TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON STATE TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON VEGETATION TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON WATERLEVEL_FIXATION TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON WATER_BODY TO PDB_ADMIN;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOCUMENT TO PDB_ADMIN;

GRANT SELECT ON SEQ_PDB TO PDB_ADMIN;

-- Version endgültig setzen
UPDATE INFO set value='0.0.3'  where key ='Version';
commit;