package org.kalypso.model.wspm.pdb.db.mapping;

// default package
// Generated May 19, 2011 4:16:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

import com.vividsolutions.jts.geom.LineString;

/**
 * CrossSectionParts generated by hbm2java
 */
@Entity
@Table(name = "CROSS_SECTION_PARTS", schema = "PDB_ADMIN")
public class CrossSectionParts implements java.io.Serializable
{
  private LineString line;

  private String crossSectionPart;

  private CrossSections crossSections;

  private String category;

  private Set<Points> pointses = new HashSet<Points>( 0 );

  public CrossSectionParts( )
  {
  }

  public CrossSectionParts( final String crossSectionPart, final CrossSections crossSections, final String category )
  {
    this.crossSectionPart = crossSectionPart;
    this.crossSections = crossSections;
    this.category = category;
  }

  public CrossSectionParts( final String crossSectionPart, final CrossSections crossSections, final String category, final Set<Points> pointses )
  {
    this.crossSectionPart = crossSectionPart;
    this.crossSections = crossSections;
    this.category = category;
    this.pointses = pointses;
  }

  @Id
  @Column(name = "CROSS_SECTION_PART", unique = true, nullable = false, length = 50)
  public String getCrossSectionPart( )
  {
    return this.crossSectionPart;
  }

  public void setCrossSectionPart( final String crossSectionPart )
  {
    this.crossSectionPart = crossSectionPart;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "CROSS_SECTION", nullable = false)
  public CrossSections getCrossSections( )
  {
    return this.crossSections;
  }

  public void setCrossSections( final CrossSections crossSections )
  {
    this.crossSections = crossSections;
  }

  @Column(name = "CATEGORY", nullable = false, length = 50)
  public String getCategory( )
  {
    return this.category;
  }

  public void setCategory( final String category )
  {
    this.category = category;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "crossSectionParts")
  public Set<Points> getPointses( )
  {
    return this.pointses;
  }

  public void setPointses( final Set<Points> pointses )
  {
    this.pointses = pointses;
  }

  @Column(name = "LINE")
  @Type(type = "org.hibernatespatial.GeometryUserType")
  public LineString getLine( )
  {
    return this.line;
  }

  public void setLine( final LineString line )
  {
    this.line = line;
  }
}
