package org.kalypso.model.wspm.pdb.db.mapping;

// default package
// Generated May 19, 2011 4:16:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roughnesses generated by hbm2java
 */
@Entity
@Table(name = "ROUGHNESSES", schema = "PDB_ADMIN")
public class Roughnesses implements java.io.Serializable
{

  private RoughnessesId id;

  private PointKinds pointKinds;

  private BigDecimal KValue;

  private BigDecimal kstValue;

  private String name;

  private String comment;

  private Set<Points> pointses = new HashSet<Points>( 0 );

  public Roughnesses( )
  {
  }

  public Roughnesses( RoughnessesId id, PointKinds pointKinds )
  {
    this.id = id;
    this.pointKinds = pointKinds;
  }

  public Roughnesses( RoughnessesId id, PointKinds pointKinds, BigDecimal KValue, BigDecimal kstValue, String name, String comment, Set<Points> pointses )
  {
    this.id = id;
    this.pointKinds = pointKinds;
    this.KValue = KValue;
    this.kstValue = kstValue;
    this.name = name;
    this.comment = comment;
    this.pointses = pointses;
  }

  @EmbeddedId
  @AttributeOverrides({ @AttributeOverride(name = "pointKind", column = @Column(name = "POINT_KIND", nullable = false, length = 50)),
      @AttributeOverride(name = "roughness", column = @Column(name = "ROUGHNESS", nullable = false, length = 50)) })
  public RoughnessesId getId( )
  {
    return this.id;
  }

  public void setId( RoughnessesId id )
  {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "POINT_KIND", nullable = false, insertable = false, updatable = false)
  public PointKinds getPointKinds( )
  {
    return this.pointKinds;
  }

  public void setPointKinds( PointKinds pointKinds )
  {
    this.pointKinds = pointKinds;
  }

  @Column(name = "K_VALUE", precision = 22, scale = 0)
  public BigDecimal getKValue( )
  {
    return this.KValue;
  }

  public void setKValue( BigDecimal KValue )
  {
    this.KValue = KValue;
  }

  @Column(name = "KST_VALUE", precision = 22, scale = 0)
  public BigDecimal getKstValue( )
  {
    return this.kstValue;
  }

  public void setKstValue( BigDecimal kstValue )
  {
    this.kstValue = kstValue;
  }

  @Column(name = "NAME", length = 100)
  public String getName( )
  {
    return this.name;
  }

  public void setName( String name )
  {
    this.name = name;
  }

  @Column(name = "Comment")
  public String getComment( )
  {
    return this.comment;
  }

  public void setComment( String comment )
  {
    this.comment = comment;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "roughnesses")
  public Set<Points> getPointses( )
  {
    return this.pointses;
  }

  public void setPointses( Set<Points> pointses )
  {
    this.pointses = pointses;
  }

}
