package org.kalypso.model.wspm.pdb.db.mapping;

// default package
// Generated May 19, 2011 4:16:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.kalypso.commons.java.util.AbstractModelObject;
import org.kalypso.model.wspm.pdb.db.constants.StateConstants;

/**
 * States generated by hbm2java
 */
@Entity
@Table(name = "STATES", schema = "PDB_ADMIN")
public class States extends AbstractModelObject implements java.io.Serializable, StateConstants
{
  private String state;

  private char isstatezero;

  private Date creationDate;

  private Date editingDate;

  private String editingUser;

  private Date measurementDate;

  private String source;

  private String comment;

  private Set<CrossSections> crossSectionses = new HashSet<CrossSections>( 0 );

  public States( )
  {
  }

  public States( final String state, final char isstatezero, final Date creationDate, final Date editingDate, final String editingUser )
  {
    this.state = state;
    this.isstatezero = isstatezero;
    this.creationDate = creationDate;
    this.editingDate = editingDate;
    this.editingUser = editingUser;
  }

  public States( final String state, final char isstatezero, final Date creationDate, final Date editingDate, final String editingUser, final Date measurementDate, final String source, final String comment, final Set<CrossSections> crossSectionses )
  {
    this.state = state;
    this.isstatezero = isstatezero;
    this.creationDate = creationDate;
    this.editingDate = editingDate;
    this.editingUser = editingUser;
    this.measurementDate = measurementDate;
    this.source = source;
    this.comment = comment;
    this.crossSectionses = crossSectionses;
  }

  @Id
  @Column(name = "STATE", unique = true, nullable = false, length = 100)
  public String getState( )
  {
    return this.state;
  }

  public void setState( final String state )
  {
    final Object oldValue = this.state;

    this.state = state;

    firePropertyChange( PROPERTY_STATE, oldValue, state );
  }

  @Column(name = "ISSTATEZERO", nullable = false, length = 1)
  public char getIsstatezero( )
  {
    return this.isstatezero;
  }

  public void setIsstatezero( final char isstatezero )
  {
    final Object oldValue = this.isstatezero;

    this.isstatezero = isstatezero;

    firePropertyChange( PROPERTY_ISSTATEZERO, oldValue, isstatezero );
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "CREATION_DATE", nullable = false, length = 7)
  public Date getCreationDate( )
  {
    return this.creationDate;
  }

  public void setCreationDate( final Date creationDate )
  {
    final Object oldValue = this.creationDate;

    this.creationDate = creationDate;

    firePropertyChange( PROPERTY_CREATIONDATE, oldValue, creationDate );
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "EDITING_DATE", nullable = false, length = 7)
  public Date getEditingDate( )
  {
    return this.editingDate;
  }

  public void setEditingDate( final Date editingDate )
  {
    final Object oldValue = this.editingDate;

    this.editingDate = editingDate;

    firePropertyChange( PROPERTY_EDITINGDATE, oldValue, editingDate );
  }

  @Column(name = "EDITING_USER", nullable = false, length = 50)
  public String getEditingUser( )
  {
    return this.editingUser;
  }

  public void setEditingUser( final String editingUser )
  {
    final Object oldValue = this.editingUser;

    this.editingUser = editingUser;

    firePropertyChange( PROPERTY_EDITINGUSER, oldValue, editingUser );
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "MEASUREMENT_DATE", length = 7)
  public Date getMeasurementDate( )
  {
    return this.measurementDate;
  }

  public void setMeasurementDate( final Date measurementDate )
  {
    final Object oldValue = this.measurementDate;

    this.measurementDate = measurementDate;

    firePropertyChange( PROPERTY_MEASUREMENTDATE, oldValue, measurementDate );
  }

  @Column(name = "SOURCE")
  public String getSource( )
  {
    return this.source;
  }

  public void setSource( final String source )
  {
    final Object oldValue = this.source;

    this.source = source;

    firePropertyChange( PROPERTY_SOURCE, oldValue, source );
  }

  @Column(name = "description")
  public String getComment( )
  {
    return this.comment;
  }

  public void setComment( final String comment )
  {
    final Object oldValue = this.comment;

    this.comment = comment;

    firePropertyChange( PROPERTY_COMMENT, oldValue, comment );
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "states")
  public Set<CrossSections> getCrossSectionses( )
  {
    return this.crossSectionses;
  }

  public void setCrossSectionses( final Set<CrossSections> crossSectionses )
  {
    final Object oldValue = this.crossSectionses;

    this.crossSectionses = crossSectionses;

    firePropertyChange( PROPERTY_CROSSSECTIONSES, oldValue, crossSectionses );
  }

}
