/* This file was generated by Kalypso, Copyright 2011 Kalypso Contributors */
package org.kalypso.model.wspm.pdb.ui.internal;
public interface IPdbHelp
{
  String CONTEXT_PDB_USER_MANUAL = WspmPdbUiPlugin.PLUGIN_ID + ".UserManual"; //$NON-NLS-1$
}
