<definitions name="Gaja3dResourceFactory"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://org.kalypso.gaja3d.service/factory"
	xmlns:tns="http://org.kalypso.gaja3d.service/factory"
	xmlns:wsrp="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd"
	xmlns:wsrpw="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.wsdl"
	xmlns:wsrlw="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.wsdl" 
	xmlns:wsdlpp="http://www.globus.org/namespaces/2004/10/WSDLPreprocessor"
	xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/03/addressing"
	xmlns:wsntw="http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl"
	xmlns:wps="http://www.opengeospatial.net/wps"
	xmlns:ows="http://www.opengeospatial.net/ows">
	
<!--============================================================ 
	
						I M P O R T S
	
	============================================================-->

<import namespace="http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl"
	location="../wsrf/notification/WS-BaseN.wsdl" />
<import namespace="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.wsdl"
	location="../wsrf/properties/WS-ResourceProperties.wsdl" />
<import namespace="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.wsdl"
	location="../wsrf/lifetime/WS-ResourceLifetime.wsdl" />

<!--============================================================

                      T Y P E S
                      
  ============================================================-->
<types>
<xsd:schema targetNamespace="http://org.kalypso.gaja3d.service/factory"
    xmlns:tns="http://org.kalypso.gaja3d.service/factory"
    xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/03/addressing"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:import 
	    namespace="http://schemas.xmlsoap.org/ws/2004/03/addressing"
	    schemaLocation="../ws/addressing/WS-Addressing.xsd" />


	<!-- REQUESTS AND RESPONSES -->

	<xsd:element name="createResource">
		<xsd:complexType/>
	</xsd:element>
	<xsd:element name="createResourceResponse">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="wsa:EndpointReference"/>
		</xsd:sequence>
	</xsd:complexType>
	</xsd:element>
        
</xsd:schema>
</types>


<!--============================================================

                       M E S S A G E S
                      
  ============================================================-->
<message name="CreateResourceRequest">
	<part name="request" element="tns:createResource"/>
</message>
<message name="CreateResourceResponse">
	<part name="response" element="tns:createResourceResponse"/>
</message>



<!--============================================================

                       P O R T T Y P E
                      
  ============================================================-->
<portType name="Gaja3dResourceFactoryPortType">

	<operation name="createResource">
		<input message="tns:CreateResourceRequest"/>
		<output message="tns:CreateResourceResponse"/>
	</operation>

</portType>

</definitions>
