<?xml version="1.0" encoding="WINDOWS-1252"?>
<ns3:TestFeatureCollection xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ns2="http://www.opengis.net/gml" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns3="org.kalypso.test.testFeature" xs:schemaLocation="org.kalypso.test.testFeature ./schema/testFeature.xsd" ns2:fid="root">
 <ns3:testFeatureMember>
  <ns3:TestFeature ns2:fid="original">
   <ns2:description>description</ns2:description>
   <ns2:name>name</ns2:name>
   <ns3:duration/>
   <ns3:string>string</ns3:string>
   <ns3:ENTITIES/>
   <ns3:boolean>true</ns3:boolean>
   <ns3:base64Binary/>
   <ns3:float>1.0</ns3:float>
   <ns3:decimal>1.0</ns3:decimal>
   <ns3:integer>1</ns3:integer>
   <ns3:long>1</ns3:long>
   <ns3:int>1</ns3:int>
   <ns3:short>1</ns3:short>
   <ns3:byte>1</ns3:byte>
   <ns3:double>1.0</ns3:double>
   <ns3:QName/>
  </ns3:TestFeature>
 </ns3:testFeatureMember>
 <ns3:testFeatureMember>
  <ns3:TestFeature ns2:fid="ADD">
   <ns2:description>description</ns2:description>
   <ns2:name>name</ns2:name>
   <ns3:duration/>
   <ns3:string>string</ns3:string>
   <ns3:ENTITIES/>
   <ns3:boolean>true</ns3:boolean>
   <ns3:base64Binary/>
   <ns3:float>3.5</ns3:float>
   <ns3:decimal>3.5</ns3:decimal>
   <ns3:integer>3</ns3:integer>
   <ns3:long>3</ns3:long>
   <ns3:int>3</ns3:int>
   <ns3:short>3</ns3:short>
   <ns3:byte>3</ns3:byte>
   <ns3:double>3.5</ns3:double>
   <ns3:QName/>
  </ns3:TestFeature>
 </ns3:testFeatureMember>
 <ns3:testFeatureMember>
  <ns3:TestFeature ns2:fid="MULTIPLY">
   <ns2:description>description</ns2:description>
   <ns2:name>name</ns2:name>
   <ns3:duration/>
   <ns3:string>string</ns3:string>
   <ns3:ENTITIES/>
   <ns3:boolean>true</ns3:boolean>
   <ns3:base64Binary/>
   <ns3:float>8.75</ns3:float>
   <ns3:decimal>8.75</ns3:decimal>
   <ns3:integer>7</ns3:integer>
   <ns3:long>7</ns3:long>
   <ns3:int>7</ns3:int>
   <ns3:short>7</ns3:short>
   <ns3:byte>7</ns3:byte>
   <ns3:double>8.75</ns3:double>
   <ns3:QName/>
  </ns3:TestFeature>
 </ns3:testFeatureMember>
 <ns3:testFeatureMember>
  <ns3:TestFeature ns2:fid="SUBTRACT">
   <ns2:description>description</ns2:description>
   <ns2:name>name</ns2:name>
   <ns3:duration/>
   <ns3:string>string</ns3:string>
   <ns3:ENTITIES/>
   <ns3:boolean>true</ns3:boolean>
   <ns3:base64Binary/>
   <ns3:float>6.25</ns3:float>
   <ns3:decimal>6.25</ns3:decimal>
   <ns3:integer>4</ns3:integer>
   <ns3:long>4</ns3:long>
   <ns3:int>4</ns3:int>
   <ns3:short>4</ns3:short>
   <ns3:byte>4</ns3:byte>
   <ns3:double>6.25</ns3:double>
   <ns3:QName/>
  </ns3:TestFeature>
 </ns3:testFeatureMember>
 <ns3:testFeatureMember>
  <ns3:TestFeature ns2:fid="DIVIDE">
   <ns2:description>description</ns2:description>
   <ns2:name>name</ns2:name>
   <ns3:duration/>
   <ns3:string>string</ns3:string>
   <ns3:ENTITIES/>
   <ns3:boolean>true</ns3:boolean>
   <ns3:base64Binary/>
   <ns3:float>2.5</ns3:float>
   <ns3:decimal>2.5</ns3:decimal>
   <ns3:integer>1</ns3:integer>
   <ns3:long>1</ns3:long>
   <ns3:int>1</ns3:int>
   <ns3:short>1</ns3:short>
   <ns3:byte>1</ns3:byte>
   <ns3:double>2.5</ns3:double>
   <ns3:QName/>
  </ns3:TestFeature>
 </ns3:testFeatureMember>
</ns3:TestFeatureCollection>
