//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.30 at 03:28:54 PM CEST 
//


package com.google.earth.kml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

import com.google.earth.kml.RefreshModeEnum;


/**
 * <p>Java class for refreshModeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="refreshModeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="onChange"/>
 *     &lt;enumeration value="onInterval"/>
 *     &lt;enumeration value="onExpire"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum RefreshModeEnum {

    @XmlEnumValue("onChange")
    ON_CHANGE("onChange"),
    @XmlEnumValue("onExpire")
    ON_EXPIRE("onExpire"),
    @XmlEnumValue("onInterval")
    ON_INTERVAL("onInterval");
    private final String value;

    RefreshModeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RefreshModeEnum fromValue(String v) {
        for (RefreshModeEnum c: RefreshModeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
