<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<NAModellControl xmlns="org.kalypso.namodell.control" xmlns:gml="http://www.opengis.net/gml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="org.kalypso.namodell.control
../../schema/nacontrol.xsd" fid="ID000000">
	<editor>Editor</editor>
	<description>Beschreibung</description>
	<comment>Kommentar</comment>
	<calctime>2001-12-17T09:30:47-05:00</calctime>
<!-- 
1995 09 01 00
1995 09 15 00
-->
	<startsimulation>1995-09-01T00:00:00-02:00</startsimulation>
	<startforecast>1995-09-04T12:00:00-02:00</startforecast>
	<endsimulation>1995-09-15T00:00:00-02:00</endsimulation>
	<timeStep>24</timeStep>
	<tmp>true</tmp>
	<pre>1</pre>
	<sch>0</sch>
	<bof>true</bof>
	<bsp>0</bsp>
	<gws>0</gws>
	<qgs>1</qgs>
	<qgg>false</qgg>
	<qna>false</qna>
	<qif>0</qif>
	<qvs>0</qvs>
	<qbs>0</qbs>
	<qt1>0</qt1>
	<qtg>0</qtg>
	<qgw>0</qgw>
	<kap>0</kap>
	<vet>0</vet>
	<hyd>0</hyd>
	<bil>0</bil>
	<nmq>0</nmq>
	<spi>0</spi>
	<sub>0</sub>
	<sph>0</sph>
	<spv>0</spv>
	<spn>0</spn>
	<vep>0</vep>
	<automaticCallibration>0</automaticCallibration>
	<Catchments>//Catchment[@fid="Catchment1002" or @fid="Catchment1003"]</Catchments>
	<CatchmentsBianf>2</CatchmentsBianf>
	<CatchmentsFaktorRetobTetint>2</CatchmentsFaktorRetobTetint>
	<CatchmentsFaktn>2</CatchmentsFaktn>
	<CatchmentsFaktorAigw>2</CatchmentsFaktorAigw>
	<KMChannels>//KMChannel[@fid="KMChannel3003" or @fid="KMChannel1003"]</KMChannels>
	<KMChannelsFaktorRkf>2</KMChannelsFaktorRkf>
	<KMChannelsFaktorRnf>2</KMChannelsFaktorRnf>
	<rootNode>Node1600</rootNode>
	<pegelZR/>
	<qberechnetZR/>
</NAModellControl>
