! THIS MODULE READ A SEPERATE DATA FILE ; WHICH INCLUDE THE PROFILES DATA REQUIRED FOR BANK
! EVOLUTION SIMULATION.
module ASSIGNROFILES

USE TYPES
USE INIT_TYPE
USE share_profile,only :BANKPROFILES
!USE BLK10MOD,only : IPROFIN

IMPLICIT NONE 

SAVE 
!TYPE (PROFILE ), DIMENSION (:),allocatable, TARGET :: BANKPROFILES
INTEGER                                :: SIZ

CONTAINS

SUBROUTINE READPROFILES (PROFILEUNIT)
IMPLICIT NONE

INTEGER                       , INTENT (IN)  :: PROFILEUNIT

INTEGER                                     :: ISTAT , I , J

!OPEN (UNIT=168 ,FILENAME = PROFILENAME STATUS='OLD', ACTION='READ', IOSTAT=istat)

!CALL file_error (PROFILENAME, istat)

write (*,*) 'entering into readprofiles subroutine...'
write (*,*)
write (*,*)' the file unit is : ', PROFILEUNIT
!write (*,*)' the file unit is : ', IPROFIN

READ (PROFILEUNIT,*,IOSTAT=istat)SIZ
IF (ISTAT/=0) THEN
WRITE (*,*) 'FAILURE BY reading the profile data SIZ....'
stop
END IF

write (*,*)' the number of profiles is : ', siz



ALLOCATE ( BANKPROFILES (SIZ), stat=ISTAT)

IF (ISTAT/=0) THEN
WRITE (*,*) 'FAILURE BY ALLOCATION OF PROFILE ARRAY IN SUBROUTINE READPROFILE....'
stop
END IF

! INITIALISE THE ARRAY OF BANKPROFILES WITH ARRAY SIZE OF SIZ.
CALL INIT_PROFILE(BANKPROFILES,SIZ)

DO I = 1,SIZ

READ (PROFILEUNIT,*) BANKPROFILES(I).LNOSE ,BANKPROFILES(I).RNOSE , BANKPROFILES(I).LFRONT ,BANKPROFILES(I).RFRONT , BANKPROFILES(I).MAX_NODES
IF (ISTAT/=0) THEN
WRITE (*,*) 'FAILURE BY reading the profile data, nose,...'
stop
END IF
write (*,*)BANKPROFILES(I).LNOSE ,BANKPROFILES(I).RNOSE , BANKPROFILES(I).LFRONT ,BANKPROFILES(I).RFRONT , BANKPROFILES(I).MAX_NODES
 DO J = 1 , BANKPROFILES(I).MAX_NODES
   
   READ (PROFILEUNIT,127) BANKPROFILES(I).PRNODE(J).FE_NODENUMBER, BANKPROFILES(I).PRNODE(J).DISTANCE ,BANKPROFILES(I).PRNODE(J).ELEVATION , BANKPROFILES(I).PRNODE(J).ATTRIBUTE
 127 FORMAT (1X,I7,2X, F4.1,1x,F7.4,1X, A9)
 IF (ISTAT/=0) THEN
WRITE (*,*) 'FAILURE BY reading the profile data, variables...'
stop
END IF
write (*,127)BANKPROFILES(I).PRNODE(J).FE_NODENUMBER, BANKPROFILES(I).PRNODE(J).DISTANCE ,BANKPROFILES(I).PRNODE(J).ELEVATION , BANKPROFILES(I).PRNODE(J).ATTRIBUTE 
 END DO
END DO   
CLOSE (PROFILEUNIT)
END SUBROUTINE READPROFILES
end module ASSIGNROFILES