! THIS MODULE READS A SEPERATE DATA FILE , WHICH INCLUDES THE PROFILES DATA REQUIRED FOR BANK
! EVOLUTION SIMULATION AND ASSIGNED THE DATA TO THE ARRAY BANKPROFILES.
! IT READS FIRST THE TOTAL NUMBER OF BANKPROFILES GIVEN AS 'SIZ' AND READS THE AVAILABLE PROFILE
! DATA (THE NUMBER OF PROFILES MIGHT BE LESS THAN 'SIZ', IN THE CASE A FEW PRF ATTRIBUTES IN 
! CONTROL.R10 ARE ZERO)
module ASSIGNROFILES

USE TYPES
USE INIT_TYPE
USE share_profile,only :BANKPROFILES
!USE BLK10MOD,only : IPROFIN

IMPLICIT NONE 

SAVE 
!TYPE (PROFILE ), DIMENSION (:),allocatable, TARGET :: BANKPROFILES
INTEGER                                :: SIZ

CONTAINS

SUBROUTINE READPROFILES (PROFILEUNIT,CURRENTPROFILE)
IMPLICIT NONE

INTEGER                       , INTENT (IN)  :: PROFILEUNIT
INTEGER                       , INTENT (OUT) :: CURRENTPROFILE

INTEGER                                      :: ISTAT , I , J, ContiLineNumber
CHARACTER (LEN = 18)                         :: TEMPCHAR

!OPEN (UNIT=168 ,FILENAME = PROFILENAME STATUS='OLD', ACTION='READ', IOSTAT=istat)

!CALL file_error (PROFILENAME, istat)

WRITE (*,*) 'entering into readprofiles subroutine...'
WRITE (*,*)
WRITE (*,*)' the file unit is : ', PROFILEUNIT
!write (*,*)' the file unit is : ', IPROFIN

READ (PROFILEUNIT,*,IOSTAT=istat)SIZ

IF (ISTAT/=0) THEN
 WRITE (*,*) 'FAILURE BY reading the profile data SIZ....'
 pause
 stop
END IF

WRITE (*,*)' the number of profiles is : ', siz

ALLOCATE ( BANKPROFILES (SIZ), stat=ISTAT)

IF (ISTAT/=0) THEN
 WRITE (*,*) 'FAILURE BY ALLOCATION OF PROFILE ARRAY IN SUBROUTINE READPROFILE....'
 pause
 stop
END IF

! INITIALISE THE ARRAY OF BANKPROFILES WITH ARRAY SIZE OF SIZ.
CALL INIT_PROFILE(BANKPROFILES,SIZ)

I = 0
!DO I = 1,SIZ

MN: Do 

! READ THE CURRENT NUMBER OF PROFILE.
I = I + 1
IF (I > siz) exit MN
IF ( PROFILEUNIT == 731) THEN                                 ! if a restart file should be read.

  READ (PROFILEUNIT,FMT = 121,IOSTAT = ISTAT)TEMPCHAR, I

  IF (ISTAT > 0) THEN
    WRITE (*,*) 'FAILURE BY reading the profile data in retsart file,..., at line :', I
    pause
    stop
  ELSEIF (ISTAT == -1 ) THEN
    EXIT MN
  END IF

  READ (PROFILEUNIT,FMT = 121,IOSTAT = ISTAT)TEMPCHAR, ContiLineNumber
  BANKPROFILES(I).CL_NUMBER = ContiLineNumber

ENDIF

READ (PROFILEUNIT,*,IOSTAT = ISTAT) BANKPROFILES(I).LNOSE ,BANKPROFILES(I).RNOSE , BANKPROFILES(I).LFRONT , &
&                                   BANKPROFILES(I).RFRONT , BANKPROFILES(I).MAX_NODES

IF (ISTAT > 0) THEN
 WRITE (*,*) 'FAILURE BY reading the profile data, nose,..., at line :', I
  pause
  stop
ELSEIF (ISTAT == -1 ) THEN
  EXIT MN
END IF

IF ( PROFILEUNIT == 731) THEN                                 ! if a restart file should be read.

  READ (PROFILEUNIT,FMT = *)TEMPCHAR

ENDIF  

write (*,*)BANKPROFILES(I).LNOSE ,BANKPROFILES(I).RNOSE , BANKPROFILES(I).LFRONT ,BANKPROFILES(I).RFRONT , BANKPROFILES(I).MAX_NODES
 
 DO J = 1 , BANKPROFILES(I).MAX_NODES
   
   READ (PROFILEUNIT,127, IOSTAT = ISTAT ) BANKPROFILES(I).PRNODE(J).FE_NODENUMBER, BANKPROFILES(I).PRNODE(J).DISTANCE ,&
   &                                       BANKPROFILES(I).PRNODE(J).ELEVATION , BANKPROFILES(I).PRNODE(J).ATTRIBUTE

 127 FORMAT (1x,I7,2x,F8.4,2x,f7.4, 1x,a9)
 
 IF (ISTAT/=0) THEN
  WRITE (*,*) 'FAILURE BY reading the profile data, variables...'
  pause
  stop
END IF

WRITE (*,127)BANKPROFILES(I).PRNODE(J).FE_NODENUMBER, BANKPROFILES(I).PRNODE(J).DISTANCE ,& 
&            BANKPROFILES(I).PRNODE(J).ELEVATION , BANKPROFILES(I).PRNODE(J).ATTRIBUTE 

END DO
END DO MN  

CURRENTPROFILE = I
121 Format (a18, T26,I6)
CLOSE (PROFILEUNIT)

END SUBROUTINE READPROFILES

END MODULE ASSIGNROFILES