/******************************************************
				PROTOTYPEN    fuer dis_prof.cpp

******************************************************/

#ifndef _DIS_PROF_H_INCLUDED_
#define _DIS_PROF_H_INCLUDED_

void win120_loesche_edit_felder(void); // wspw120
void win116_loesche_edit_felder(void); // hier, wspd116, wspw116
void display_prof120(WINDOW *win); // oft
void display_prof116(WINDOW *win); // oft

#endif _DIS_PROF_H_INCLUDED_