////////////////
// profproj.h //
////////////////
#ifndef _PROFPROJ_H_INCLUDED_
#define _PROFPROJ_H_INCLUDED_

void teste_projekt_profile(int drucken); // aufnehm, wspw120, waspila
void teste_str_datei(void); // wspd208
void ermittle_schluessel_aus_profildatei(char fss_name[15]); // aufnehm
void haenge_zustand_an_zsd(char profil_name[15]); // aufnehm, wspd210
void teste_physisch_loeschen(char name[15]); // wspd136


#endif _PROFPROJ_H_INCLUDED_