/*****************************************************************
	Datenblockkennzeichen für Profildatei
					L W A + BCE
******************************************************************/
#define GELAENDEHOEHE   1     // Geländehöhe NN+m
#define TRENNFLAECHEN   2     // Trennflächen
#define RAUHIGKEIT      3     // Rauhigkeit k-s [m]
#define RAUHIGKEIT_KST  4     // Rauhigkeit KST
#define DURCHST_BEREICH 5     // Durchströmte Bereiche
#define UK_BRUECKE      6     // UK-Bruecke
#define OK_BRUECKE      7     // OK-Bruecke
#define AXM             8    // AX m
#define AYM             9    // AY m
#define DPM             10    // DP m
#define OK_WEHRS        11    // OK-Wehr
#define GELAENDE2       12    // 2.Geländehöhe
#define FLAECHE         13    //Fläche
#define BUHNE			      14    //Sonderbauwerk / Buhne
#define MODELLGRENZEN   15    //Haptöffnung
#define SCHUETZ         16    //Schütz

#define KREISSEGM       20    // Kreisegment
#define SVA_WERT		    21
#define OK_GELAENDE 	  22	   //Gelände über Sonderprofil
#define KASTEN			    23    // Kastenprofil
#define LWA_FELDER		  24    // u-Werte bei Sonderprofil Wehr
#define GAUSSRUECK      25    //Gauss-Profil mit Rücksprüngen
#define GAUSS           26    //Gauss-Krüger-Koordinaten
#define RECHTSWERT      27    // Rechtswertkoordinate
#define HOCHWERT        28    // Hochwertkoordinate

#define PUNKT_NR			  40
#define STATION			    41
#define WASSERSP1       42    // Wasserspiegel NN + m  HQ 1  -Best
#define WASSERSP100     43    // Wasserspiegel NN + m  HQ 100-Best
#define WASSERSP5       44    // Wasserspiegel NN + m  HQ 5  -Best
#define BORDVOLL			  45    // Bordvollpunkte
#define TRENN_WEHR      46    // Trennlinie Wehr
#define STATION_FIX		  47

/*    Sonderprofile      */
#define MAUL            60    // MAULPROFIL
#define EIPROFIL        61    // EIPROFIL
#define KREIS           62    // KREISPROFIL

#define ARMCO84			    70	   // Sonderprofil LWA
#define ARMCO71			    71	   // Sonderprofil LWA
#define NWRINNE         72    // Niedrigwasserrinne
#define FUELLHOEHE      73    //Füllhöhen-Profil
#define NAU_MED         74    // Naudascher-Medlarz

#define TRAPEZ				  80    //Trapezprofil

#define COMMENT         97    // Kommentar in Profildatei

#define UNKNOWN			    98    // unbekannter / anderer Datensatz
#define NEU_DS          99    // neuer Datensatz  (anlegen)
#define DATPLOT         100   // Plotterdatensatz
/********************************************************************/

