#ifndef _VAERZWEIG_H_
#define _VAERZWEIG_H_

void teste_str_verzweigt(void); // aufnehm, wspd208, wspw120
void copy_old_to_new_strverweigt(char *old_file, char *new_file ); // aufnehm
void copy_vzk_default_datei(char *old_zustandsdatei, char *new_zustandsdatei); // dito
void schreibe_slist_verzweigt(); // dito
void alte_str_in_slist(); // dito
void teste_str_verzweigt_intern(void);//Dick 31.03.99 // wspd136
void vzk_block();//Dick 7.09.99 // wspm001


#endif // _VAERZWEIG_H_