/*
 * File generated by Octopus on 25.06.2007 13:30:41
 */
package org.kalypso.kalypso1d2d.octopus.test.calculationUnit;

import java.util.ArrayList;
import java.util.List;

/** Class ...
 */
public class MergeElement2D {
	static private boolean usesAllInstances = false;
	static private List allInstances = new ArrayList();

	/** Default constructor for Element2D
	 */
	public MergeElement2D() {
		if ( usesAllInstances ) {
			allInstances.add(this);
		}
	}

	/** Checks all invariants of this object and returns a list of messages about broken invariants
	 */
	public List checkAllInvariants() {
		List /* InvariantError */ result = new ArrayList /* InvariantError */();
		return result;
	}
	
	/** Implements a check on the multiplicities of all attributes and association ends
	 */
	public List checkMultiplicities() {
		List /* InvariantError */ result = new ArrayList /* InvariantError */();
		return result;
	}
	
	/** Returns the default identifier for Element2D
	 */
	public String getIdString() {
		String result = "";
		result = "no ID found";
		return result;
	}
	
	/** Implements the OCL allInstances operation
	 */
	static public List allInstances() {
		if ( !usesAllInstances ) {
			throw new RuntimeException("allInstances is not implemented for this class. Set usesAllInstances to true, if you want allInstances() implemented.");
		}
		return allInstances;
	}

}