//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.17 at 11:35:00 AM CEST 
//


package de.tu_harburg.wb.kalypso.rrm.kalininmiljukov;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KalininMiljukovType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KalininMiljukovType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="riverName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kmStart" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="kmEnd" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="filePattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profile" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="positionKM" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KalininMiljukovType", propOrder = {
    "riverName",
    "kmStart",
    "kmEnd",
    "path",
    "filePattern",
    "profile"
})
public class KalininMiljukovType {

    protected String riverName;
    protected Double kmStart;
    protected Double kmEnd;
    @XmlElement(required = true)
    protected String path;
    @XmlElement(required = true)
    protected String filePattern;
    protected List<KalininMiljukovType.Profile> profile;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the riverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiverName() {
        return riverName;
    }

    /**
     * Sets the value of the riverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiverName(String value) {
        this.riverName = value;
    }

    /**
     * Gets the value of the kmStart property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getKmStart() {
        return kmStart;
    }

    /**
     * Sets the value of the kmStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setKmStart(Double value) {
        this.kmStart = value;
    }

    /**
     * Gets the value of the kmEnd property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getKmEnd() {
        return kmEnd;
    }

    /**
     * Sets the value of the kmEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setKmEnd(Double value) {
        this.kmEnd = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the filePattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilePattern() {
        return filePattern;
    }

    /**
     * Sets the value of the filePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilePattern(String value) {
        this.filePattern = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KalininMiljukovType.Profile }
     * 
     * 
     */
    public List<KalininMiljukovType.Profile> getProfile() {
        if (profile == null) {
            profile = new ArrayList<KalininMiljukovType.Profile>();
        }
        return this.profile;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="positionKM" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "file"
    })
    public static class Profile {

        @XmlElement(required = true)
        protected String file;
        @XmlAttribute
        protected Boolean enabled;
        @XmlAttribute
        protected Double positionKM;

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFile(String value) {
            this.file = value;
        }

        /**
         * Gets the value of the enabled property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isEnabled() {
            return enabled;
        }

        /**
         * Sets the value of the enabled property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setEnabled(Boolean value) {
            this.enabled = value;
        }

        /**
         * Gets the value of the positionKM property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getPositionKM() {
            return positionKM;
        }

        /**
         * Sets the value of the positionKM property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setPositionKM(Double value) {
            this.positionKM = value;
        }

    }

}
