package org.kalypso.model.wspm.pdb.db.mapping;

// default package
// Generated May 19, 2011 4:16:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vegetations generated by hbm2java
 */
@Entity
@Table(name = "VEGETATIONS", schema = "PDB_ADMIN")
public class Vegetations implements java.io.Serializable
{

  private VegetationsId id;

  private PointKinds pointKinds;

  private BigDecimal dp;

  private BigDecimal ax;

  private BigDecimal ay;

  private String name;

  private String comment;

  private Set<Points> pointses = new HashSet<Points>( 0 );

  public Vegetations( )
  {
  }

  public Vegetations( VegetationsId id, PointKinds pointKinds, BigDecimal dp, BigDecimal ax, BigDecimal ay )
  {
    this.id = id;
    this.pointKinds = pointKinds;
    this.dp = dp;
    this.ax = ax;
    this.ay = ay;
  }

  public Vegetations( VegetationsId id, PointKinds pointKinds, BigDecimal dp, BigDecimal ax, BigDecimal ay, String name, String comment, Set<Points> pointses )
  {
    this.id = id;
    this.pointKinds = pointKinds;
    this.dp = dp;
    this.ax = ax;
    this.ay = ay;
    this.name = name;
    this.comment = comment;
    this.pointses = pointses;
  }

  @EmbeddedId
  @AttributeOverrides({ @AttributeOverride(name = "pointKind", column = @Column(name = "POINT_KIND", nullable = false, length = 50)),
      @AttributeOverride(name = "vegetation", column = @Column(name = "VEGETATION", nullable = false, length = 50)) })
  public VegetationsId getId( )
  {
    return this.id;
  }

  public void setId( VegetationsId id )
  {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "POINT_KIND", nullable = false, insertable = false, updatable = false)
  public PointKinds getPointKinds( )
  {
    return this.pointKinds;
  }

  public void setPointKinds( PointKinds pointKinds )
  {
    this.pointKinds = pointKinds;
  }

  @Column(name = "DP", nullable = false, precision = 22, scale = 0)
  public BigDecimal getDp( )
  {
    return this.dp;
  }

  public void setDp( BigDecimal dp )
  {
    this.dp = dp;
  }

  @Column(name = "AX", nullable = false, precision = 22, scale = 0)
  public BigDecimal getAx( )
  {
    return this.ax;
  }

  public void setAx( BigDecimal ax )
  {
    this.ax = ax;
  }

  @Column(name = "AY", nullable = false, precision = 22, scale = 0)
  public BigDecimal getAy( )
  {
    return this.ay;
  }

  public void setAy( BigDecimal ay )
  {
    this.ay = ay;
  }

  @Column(name = "NAME", length = 100)
  public String getName( )
  {
    return this.name;
  }

  public void setName( String name )
  {
    this.name = name;
  }

  @Column(name = "Comment")
  public String getComment( )
  {
    return this.comment;
  }

  public void setComment( String comment )
  {
    this.comment = comment;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "vegetations")
  public Set<Points> getPointses( )
  {
    return this.pointses;
  }

  public void setPointses( Set<Points> pointses )
  {
    this.pointses = pointses;
  }

}
