package org.kalypso.model.wspm.pdb.db.mapping;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VegetationId generated by hbm2java
 */
@Embeddable
public class VegetationId implements java.io.Serializable, CoefficientId
{
  private String m_pointKind;

  private String m_name;

  public VegetationId( )
  {
  }

  public VegetationId( final String pointKind, final String name )
  {
    m_pointKind = pointKind;
    m_name = name;
  }

  @Override
  @Column(name = "point_kind", nullable = false, length = 50)
  public String getPointKind( )
  {
    return m_pointKind;
  }

  public void setPointKind( final String pointKind )
  {
    m_pointKind = pointKind;
  }

  @Override
  @Column(name = "name", nullable = false, length = 50)
  public String getName( )
  {
    return m_name;
  }

  public void setName( final String name )
  {
    m_name = name;
  }

  @Override
  public boolean equals( final Object other )
  {
    if( (this == other) )
      return true;
    if( (other == null) )
      return false;
    if( !(other instanceof VegetationId) )
      return false;
    final VegetationId castOther = (VegetationId) other;

    return ((getPointKind() == castOther.getPointKind()) || (getPointKind() != null && castOther.getPointKind() != null && getPointKind().equals( castOther.getPointKind() )))
        && ((getName() == castOther.getName()) || (getName() != null && castOther.getName() != null && getName().equals( castOther.getName() )));
  }

  @Override
  public int hashCode( )
  {
    int result = 17;

    result = 37 * result + (getPointKind() == null ? 0 : getPointKind().hashCode());
    result = 37 * result + (getName() == null ? 0 : getName().hashCode());
    return result;
  }
}