<?xml version="1.0" encoding="US-ASCII"?>

<!--This file was created automatically by xsl2profile-->

<!--from the DocBook XSL stylesheets. Do not edit this file.-->

<!--############################################################################# 
|	$Id$
|- #############################################################################
|	$Author$
+ ############################################################################## -->
<xsl:stylesheet xmlns:doc="http://nwalsh.com/xsl/documentation/1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:exslt="http://exslt.org/common" exslt:dummy="dummy" extension-element-prefixes="exslt" exclude-result-prefixes="doc exslt" version="1.0">

	<doc:reference xmlns="" id="docbook">
		<referenceinfo xmlns="">
			<releaseinfo role="meta">
				$Id$
			</releaseinfo>
			<authorgroup>
				<author><firstname>Ramon</firstname><surname>Casellas</surname></author>
				<author><firstname>James</firstname><surname>Devenish</surname></author>
			</authorgroup>
			<copyright>
				<year>2000</year><year>2001</year><year>2002</year><year>2003</year>
				<holder>Ramon Casellas</holder>
			</copyright>
			<revhistory>
				<doc:revision rcasver="1.10"><date xmlns="">May-January 2004</date><revremark xmlns="">Major review of documentation.</revremark></doc:revision>
			</revhistory>
		</referenceinfo>
		<title xmlns="">DocBook Driver <filename>docbook.xsl</filename></title>
		<partintro xmlns="">
			<para>
				
				This is the <quote>parent</quote> stylesheet. The used
				<quote>modules</quote> are included here. The output encoding
				is <literal>text</literal> in ISO-8859-1, indented. Parameters
				may be found in
				<!--
				<link linkend="vars">vars.mod.xsl</link>,
				-->
				<link linkend="param-common">param-common.xsl</link>,
				<link linkend="param-switch">param-switch.xsl</link> and
				<link linkend="param-direct">param-direct.xsl</link>. Users
				may use this stylesheets directory or may construct their own
				<quote>customisation layer</quote> that uses
				<literal>xsl:import</literal>. Users may also override the
				<link linkend="latex.mapping">default <productname condition="noindex"><?latex \?>LaTeX</productname> mappings</link>.
				
			</para>
			<para>
				
				An <literal>id</literal> XSLT key is defined for all elements,
				matching their <sgmltag class="attribute">id</sgmltag>
				attribute, to work around <productname>xsltproc</productname>
				bugs.
				
			</para>
		</partintro>
	</doc:reference>

	<xsl:output method="text" encoding="ISO-8859-1" indent="yes"/>
	<xsl:key name="id" match="*" use="@id"/>

	<xsl:include href="common/l10n.xsl"/>
	<xsl:include href="common/common.xsl"/>
	<xsl:include href="common/gentext.xsl"/>
	<xsl:include href="common/subtitles.xsl"/>
	<xsl:include href="common/titles.xsl"/>
	<!--
	<xsl:include href="lib/lib.xsl"/>
	-->

	<xsl:include href="VERSION.xml"/>
	<xsl:include href="param-common.mod.xsl"/>
	<xsl:include href="param-switch.mod.xsl"/>
	<xsl:include href="param-direct.mod.xsl"/>
	<xsl:include href="latex.mapping.xsl"/>
	<xsl:include href="preamble.mod.xsl"/>
	<xsl:include href="labelid.mod.xsl"/>

	<xsl:include href="book-article.mod.xsl"/>

	<xsl:include href="component.mod.xsl"/>

	<xsl:include href="part-chap-app.mod.xsl"/>

	<xsl:include href="sections.mod.xsl"/>
	<xsl:include href="bridgehead.mod.xsl"/>

	<xsl:include href="abstract.mod.xsl"/>
	<xsl:include href="biblio.mod.xsl"/>
	<xsl:include href="revision.mod.xsl"/>

	<xsl:include href="admonition.mod.xsl"/>
	<xsl:include href="verbatim.mod.xsl"/>
	<xsl:include href="email.mod.xsl"/>
	<xsl:include href="sgmltag.mod.xsl"/>
	<xsl:include href="citation.mod.xsl"/>
	<xsl:include href="qandaset.mod.xsl"/>
	<xsl:include href="procedure.mod.xsl"/>
	<xsl:include href="lists.mod.xsl"/>
	<xsl:include href="callout.mod.xsl"/>

	<xsl:include href="figure.mod.xsl"/>
	<xsl:include href="graphic.mod.xsl"/>
	<xsl:include href="mediaobject.mod.xsl"/>

	<xsl:include href="index.mod.xsl"/>

	<xsl:include href="xref.mod.xsl"/>
	<xsl:include href="formal.mod.xsl"/>
	<xsl:include href="example.mod.xsl"/>
	<xsl:include href="table.mod.xsl"/>
	<xsl:include href="inline.mod.xsl"/>
	<xsl:include href="authorgroup.mod.xsl"/>
	<xsl:include href="dingbat.mod.xsl"/>
	<xsl:include href="keywords.mod.xsl"/>
	<xsl:include href="refentry.mod.xsl"/>
	<xsl:include href="glossary.mod.xsl"/>
	<xsl:include href="block.mod.xsl"/>

	<xsl:include href="synop-oop.mod.xsl"/>
	<xsl:include href="synop-struct.mod.xsl"/>

	<xsl:include href="pi.mod.xsl"/>

	<xsl:include href="footnote.mod.xsl"/>

	<xsl:include href="texmath.mod.xsl"/>
	<xsl:include href="mathelem.mod.xsl"/>
	<xsl:include href="mathml/mathml.mod.xsl"/>
	<xsl:include href="mathml/mathml.presentation.mod.xsl"/>
	<xsl:include href="mathml/mathml.content.mod.xsl"/>
	<xsl:include href="mathml/mathml.content.token.mod.xsl"/>
	<xsl:include href="mathml/mathml.content.functions.mod.xsl"/>
	<xsl:include href="mathml/mathml.content.constsymb.mod.xsl"/>

	<xsl:include href="para.mod.xsl"/>
	<xsl:include href="msgset.mod.xsl"/>

	<xsl:include href="normalize-scape.mod.xsl"/>

	<doc:template xmlns="" match="/">
		<refpurpose xmlns="">Root node</refpurpose>
		<doc:description>
			<para xmlns="">

				This template begins the conversion of a <productname condition="noindex">DocBook</productname> document to
				<productname condition="noindex"><?latex \?>LaTeX</productname>.

			</para>
		</doc:description>
		<doc:variables>
			<para xmlns="">There are no configuration variables for this template.</para>
		</doc:variables>
	</doc:template>
	<xsl:include href="../profiling/profile-mode.xsl"/><xsl:template match="/"><xsl:variable name="profiled-content"><xsl:apply-templates select="." mode="profile"/></xsl:variable><xsl:variable name="profiled-nodes" select="exslt:node-set($profiled-content)"/>
		<xsl:variable name="xsl-vendor" select="system-property('xsl:vendor')"/>
		<xsl:message>################################################################################</xsl:message>
		<xsl:message> XSLT stylesheets DocBook - LaTeX 2e                                            </xsl:message>
		<xsl:message> Reqs: LaTeX 2e installation common packages                                    </xsl:message>
		<xsl:message>################################################################################</xsl:message>
		<xsl:message> RELEASE : <xsl:value-of select="$VERSION"/>                                    </xsl:message>
		<xsl:message> VERSION : <xsl:value-of select="$CVSVERSION"/>                                 </xsl:message>
		<xsl:message>     TAG : <xsl:value-of select="$TAG"/>                                        </xsl:message>
		<xsl:message>     WWW : http://db2latex.sourceforge.net                                      </xsl:message>
		<xsl:message> SUMMARY : http://www.sourceforge.net/projects/db2latex                         </xsl:message>
		<xsl:message>  AUTHOR : Ramon Casellas  casellas@infres.enst.fr                              </xsl:message>
		<xsl:message>  AUTHOR : James Devenish  j-devenish@users.sf.net                              </xsl:message>
		<xsl:message>   USING : <xsl:call-template name="set-vendor"/>                               </xsl:message>
		<xsl:message>################################################################################</xsl:message>
		<xsl:apply-templates/>
	</xsl:template>

	<!--############################################################################# -->
	<!-- XSL Processor Vendor														  -->
	<!-- XSL Mailing Lists http://www.dpawson.co.uk/xsl/N10378.html					  -->
	<!--############################################################################# -->
	<xsl:template name="set-vendor">
		<xsl:variable name="xsl-vendor" select="system-property('xsl:vendor')"/>
		<xsl:choose>
			<xsl:when test="contains($xsl-vendor, 'SAXON 6.4')">
			<xsl:text>SAXON 6.4.X</xsl:text>
			</xsl:when>
			<xsl:when test="contains($xsl-vendor, 'SAXON 6.2')">
			<xsl:text>SAXON 6.2.X</xsl:text>
			</xsl:when>
			<xsl:when test="starts-with($xsl-vendor,'SAXON')">
			<xsl:text>SAXON</xsl:text>
			</xsl:when>
			<xsl:when test="contains($xsl-vendor,'Apache')">
			<xsl:text>XALAN</xsl:text>
			</xsl:when>
			<xsl:when test="contains($xsl-vendor,'Xalan')">
			<xsl:text>XALAN</xsl:text>
			</xsl:when>
			<xsl:when test="contains($xsl-vendor,'libxslt')">
			<xsl:text>libxslt/xsltproc</xsl:text>
			</xsl:when>
			<xsl:when test="contains($xsl-vendor,'Clark')">
			<xsl:text>XT</xsl:text>
			</xsl:when>
			<xsl:otherwise>
			<xsl:text>UNKNOWN</xsl:text>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>

	<doc:template xmlns="" match="*">
		<refpurpose xmlns="">Catches unhandled elements</refpurpose>
		<doc:description>
			<para xmlns="">

				This template emits an XSL message when <productname condition="noindex">DB2<?latex \?>LaTeX</productname> has no
				template for an element that was encountered.

			</para>
		</doc:description>
		<doc:variables>
			<para xmlns="">There are no configuration variables for this template.</para>
		</doc:variables>
	</doc:template>
	<xsl:template match="*">
		<xsl:message>DB2LaTeX: Need to process XPath match <xsl:value-of select="concat(name(..),'/',name(.))"/></xsl:message>
		<xsl:text> [</xsl:text><xsl:value-of select="name(.)"/><xsl:text>] 
</xsl:text>
		<xsl:apply-templates/> 
		<xsl:text> [/</xsl:text><xsl:value-of select="name(.)"/><xsl:text>] 
</xsl:text>
	</xsl:template>

</xsl:stylesheet>

