      MODULE BLKCDMOD
!
      REAL*8 XCEN,YCEN,RADS
      ALLOCATABLE XCEN(:),YCEN(:),RADS(:)
!
      INTEGER NKEY,IGAP,IEDGE(2,500)
!
      ALLOCATABLE NKEY(:),IGAP(:)
!
!      COMMON /C/ XCEN(MNP*2),YCEN(MNP*2),RADS(MNP*2)
!
!      COMMON /D/ NKEY(MNP*2),IGAP(MNP*2)
!
      END MODULE