CIPK  LAST UPDATE SEP 6 2004 RENAME character variable FNAM to FNAMT add error file
c-----------------------------------------------------------------optim
       subroutine optim
c---------------------------------------------------------------------c
c purpose:                                                            c
c         To optimize element ordering.                               c
c---------------------------------------------------------------------c
c Array 'perm' is created to store old number in order of new numbers.c
c---------------------------------------------------------------------c
ccc    implicit real*8 (a-h,o-z)
       return
       end
