      MODULE TSVAR
!
!ipk dec05      ALLOCATABLE CTIMEON(:,:),CTIMEOF(:,:)
      REAL HTIMEON,HTIMEOF
      ALLOCATABLE CTIMEON(:,:),CTIMEOF(:,:),HTIMEON(:,:),HTIMEOF(:,:)
!
      INTEGER NTIMSET,IYTIM,NTIMEMX
      END MODULE
!
