!
      SUBROUTINE VRTVEL
      USE BLK10MOD
      SAVE
!
      CALL SETUP
      IF(NSZF == 0) GO TO 500
      CALL FRONT(2)
!-
!......INITIALIZE DIVID
!-
      DO 300 N=1,NP
      DDHDX(N)=0.
      DDHDY(N)=0.
      DDAODX(N)=0.
      DDAODY(N)=0.
  300 DIVID(N)=0.
!-
      DO 400 N=1,NE
      IF(IMAT(N)/1000 == 2) CALL PLANAR(N)
  400 CONTINUE
      CALL VVELF
  500 CONTINUE
!-
!......RESTORE NDF FOR FUTURE ANALYSIS
!-
      NDF=6
      RETURN
      END
