create table cross_section (id int4 not null unique, creation_date timestamp not null, description varchar(255), editing_date timestamp not null, editing_user varchar(50) not null, line bytea, measurement_date timestamp, name varchar(50) not null unique, station numeric(8, 3) not null, state int4 not null, water_body int4 not null, primary key (id), unique (name));
create table cross_section_part (id int4 not null unique, category varchar(50) not null, description varchar(255), line bytea, name varchar(50) not null unique, cross_section int4 not null, primary key (id), unique (name));
create table event (id int4 not null unique, creation_date timestamp not null, description varchar(255), editing_date timestamp not null, editing_user varchar(50) not null, measurement_date timestamp, name varchar(100) not null unique, source varchar(255), type varchar(50), water_body int4 not null, primary key (id), unique (name));
create table info (key varchar(50) not null unique, value varchar(255), primary key (key));
create table point (id int4 not null unique, consecutive_num int8 not null, description varchar(255), hight numeric(8, 4), hyk varchar(50), kz varchar(50), location bytea, name varchar(50) not null, roughness_k_value numeric(8, 1), roughness_kst_value numeric(8, 1), vegetation_ax numeric(8, 3), vegetation_ay numeric(8, 3), vegetation_dp numeric(8, 3), width numeric(8, 4), cross_section_part int4 not null, roughness varchar(50), roughness_point_kind varchar(50), vegetation varchar(50), vegetation_point_kind varchar(50), primary key (id));
create table point_kind (name varchar(50) not null unique, description varchar(255), label varchar(100) not null, primary key (name));
create table roughness (name varchar(50) not null, point_kind varchar(50) not null, k_value numeric(8, 1), description varchar(255), kst_value numeric(8, 1), label varchar(100), primary key (name, point_kind));
create table state (id int4 not null unique, creation_date timestamp not null, description varchar(255), editing_date timestamp not null, editing_user varchar(50) not null, isstatezero char(1) not null, measurement_date timestamp, name varchar(100) not null unique, source varchar(255), primary key (id), unique (name));
create table vegetation (name varchar(50) not null, point_kind varchar(50) not null, ax numeric(8, 3) not null, ay numeric(8, 3) not null, description varchar(255), dp numeric(8, 3) not null, label varchar(100), primary key (name, point_kind));
create table water_body (id int4 not null unique, description varchar(255), label varchar(100) not null, name varchar(100) not null unique, riverline Geometry, primary key (id), unique (name));
create table waterlevel_fixation (id int4 not null unique, creation_date timestamp not null, description varchar(255), discharge numeric(8, 3), editing_date timestamp not null, editing_user varchar(50) not null, measurement_date timestamp, station numeric(8, 3) not null, waterlevel numeric(8, 3), event int4 not null, primary key (id));
alter table cross_section add constraint FK92AB7DE65D9546F4 foreign key (water_body) references water_body
alter table cross_section add constraint FK92AB7DE624428D73 foreign key (state) references state
alter table cross_section_part add constraint FK3BE45EAC32C0E2FA foreign key (cross_section) references cross_section
alter table event add constraint FK5C6729A5D9546F4 foreign key (water_body) references water_body
alter table point add constraint FK65E559059FEF1D3 foreign key (cross_section_part) references cross_section_part
alter table point add constraint FK65E5590FCAE211F foreign key (vegetation, vegetation_point_kind) references vegetation
alter table point add constraint FK65E5590FD88DEE3 foreign key (roughness, roughness_point_kind) references roughness
alter table roughness add constraint FKF40536909E32C9F8 foreign key (point_kind) references point_kind
alter table vegetation add constraint FK8EC7C10E9E32C9F8 foreign key (point_kind) references point_kind
alter table waterlevel_fixation add constraint FK4EEDCF3222B9E985 foreign key (event) references event